Application: Deeper Chain
w3f/Open-Grants-Program pull request #141
Opened 2020-12-03 14:44 UTC by chaosma

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

2020-12-03 14:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=141) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=141) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Chao Ma<br/>:x: hliu4atomos<br/><hr/>**Chao Ma** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=141) it.</sub>

2020-12-03 15:12 UTC, Noc2 commented
Thanks for the application. @hliu4atomos also needs to sign the CLA.

2020-12-05 06:09 UTC, chaosma commented
> Thanks for the application. @hliu4atomos also needs to sign the CLA.

Thanks for reminding! @hliu4atomos signed the CLA as well.

2020-12-07 15:01 UTC, Noc2 requested changes
Thanks for the signature. However, the costs of the grant are currently missing, see the [template]( https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)

2020-12-11 02:31 UTC, chaosma commented
> Thanks for the signature. However, the costs of the grant are currently missing, see the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)

I added the total cost in BTC based on the current BTC price. Thank you!

2020-12-11 16:16 UTC, Noc2 requested changes
Thanks for the update. However, the general grants application contained the complete project milestone 1, 2 and 3 for the same price. Is it possible to reduce the price of the open grants application accordingly?

2020-12-12 19:04 UTC, BenWhiteJam commented
Hi @chaosma as you explained it in the chat, could you also please define the deliverables into more depth?
As you stated it:
`For this OGP application, our deliverable is the micropayment pallet as well as the client code including tutorial documents. A user can use our code base (this application) together with our software(atomos) or hardware (deeper connect). In the next phase, we will add PoC and light node discovery pallets.`
Thanks!

2020-12-13 02:17 UTC, chaosma commented
> Hi @chaosma as you explained it in the chat, could you also please define the deliverables into more depth?
> As you stated it:
> `For this OGP application, our deliverable is the micropayment pallet as well as the client code including tutorial documents. A user can use our code base (this application) together with our software(atomos) or hardware (deeper connect). In the next phase, we will add PoC and light node discovery pallets.`
> Thanks!

Thanks for your feedback! I have included this in our application.

2020-12-14 11:37 UTC, Noc2 commented
Any updates regarding the price. Otherwise, we will probably discuss your general grants application again next week.

2020-12-14 14:52 UTC, hliu4atomos commented
Hi Chao,

Could you take care the price issue?

Thanks,
Hui

On 12/14/20 3:37 AM, David Hawig wrote:
>
> Any updates regarding the price. Otherwise, we will probably discuss 
> your general grants application again next week.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/w3f/Open-Grants-Program/pull/141#issuecomment-744382249>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AGZOGCIWLKI5ZIJQSFVTOJ3SUX2H7ANCNFSM4UMCMU5Q>.
>

2020-12-14 15:06 UTC, chaosma commented
> Thanks for the update. However, the general grants application contained the complete project milestone 1, 2 and 3 for the same price. Is it possible to reduce the price of the open grants application accordingly?

@Noc2  The original plan for the general grant is 100k for 3 milestones. After our discussion, we switch to apply one milestone at a time. So the 30k in general grant application actually is for milestone 1. This might be confusing. But if you think it's still high. Could you give me any advice price that you think reasonable? I am happy to modify it.

2020-12-18 08:18 UTC, Noc2 commented
@chaosma Sorry for the late reply. In this case I will close the general grants application. The current google doc of the general grants application said 10k per milestone. Given that the grants committee already had concerns about the application at this price the last time, it would really help if you could reduce the price again of the open grants application (also given the current BTC market price) and/or open source AtomOS as part of the deliveries. Once you update the application, I will share it with the rest of the committee.

2020-12-18 10:47 UTC, chaosma commented
> @chaosma Sorry for the late reply. In this case I will close the general grants application. The current google doc of the general grants application said 10k per milestone. Given that the grants committee already had concerns about the application at this price the last time, it would really help if you could reduce the price again of the open grants application (also given the current BTC market price) and/or open source AtomOS as part of the deliveries. Once you update the application, I will share it with the rest of the committee.

@Noc2 Hi, David, yeah, the BTC price increased a lot recently. I have changed the cost from 1.65 BTC to 0.5 BTC. Based on the current BTC price, the cost is close to 10k. Let me know if you have any other concerns. Thanks!

2020-12-18 12:28 UTC, Noc2 approved these changes
Looks good to me, I will share it with the rest of the team.

2020-12-18 12:58 UTC, BenWhiteJam approved these changes
Thanks for the application and updates, looking good to me as well!

2020-12-20 08:52 UTC, chaosma commented
> Looks good to me, I will share it with the rest of the team.

Cool, do we have a third reviewer? Three reviewers are required. Thanks!

2020-12-21 10:09 UTC, mmagician approved these changes
Sounds interesting, I'm looking forward to testing it!

2020-12-21 10:10 UTC, merged

2021-03-22 13:20 UTC, mmagician commented
As I'm sure you've discussed with @jimmychu0807, teams that have been successful in the hackathon will have the grant value discounted by the amount of the hackathon prize. I've created a PR for this [here](https://github.com/w3f/Open-Grants-Program/pull/324), please let me know that you're OK with the change.

2021-06-09 09:33 UTC, alxs commented
Hey @chaosma, care to share a quick update on your progress with the milestone? I see you're actively working on it, but it would be nice to get a quick update when you run into delays.

2021-07-22 11:50 UTC, semuelle commented
@chaosma, @hliu4atomos, are you still interested in working on the grant? Otherwise we would suspend it.

2021-08-03 11:59 UTC, alxs commented
@chaosma @hliu4atomos @fyang1024 @lzw65 @donileongdeepernetwork @donilan

This grant is now delayed by over 6 months. If we don't hear anything from you soon, we will terminate it in the coming days. If you can't submit within the next 2 weeks, please submit and amendment to your application to include an ETA/accurate duration.