Ares Protocol milestone 1
w3f/Open-Grants-Program pull request #176
Opened 2021-01-01 04:01 UTC by jiyilanzhou

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

2021-01-01 04:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=176) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=176) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=176) it.</sub>

2021-01-03 14:37 UTC, Noc2 approved these changes
Thanks. Looks good to me. I will share it with the rest of the team.

2021-01-03 14:44 UTC, Noc2 requested changes

2021-01-03 14:44 UTC, Noc2 commented on applications/ares_protocol.md
> +| 5. | example for demonstration | Provide  parachain oracle pallet integrate example, It replace golang with js, integrate videos and the front-end into the deliveries|
Could you change "It replace golang with js" to "it uses the scanner, which is written in js"? And generally specify the programming languages of each delivery.

2021-01-03 15:20 UTC, jiyilanzhou commented on applications/ares_protocol.md
> +| 5. | example for demonstration | Provide  parachain oracle pallet integrate example, It replace golang with js, integrate videos and the front-end into the deliveries|
I aleady has update it, and add some new worker.

2021-01-04 08:55 UTC, Noc2 commented on applications/ares_protocol.md
> +| 5. | example for demonstration | Provide  parachain oracle pallet integrate example, It replace golang with js, integrate videos and the front-end into the deliveries|
Thanks

2021-01-04 08:56 UTC, Noc2 approved these changes
Looks good. I will share it with the rest of the team.

2021-01-04 09:08 UTC, laboon approved these changes

2021-01-04 09:24 UTC, mmagician approved these changes

2021-01-04 09:24 UTC, merged