add DNFT
w3f/Open-Grants-Program pull request #188
Opened 2021-01-07 07:24 UTC by bleemer4

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

2021-01-07 07:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=188) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=188) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=188) it.</sub>

2021-01-07 15:47 UTC, Noc2 requested changes
Thanks for the application. It looks really interesting. I have a few questions: 

- Could you also integrate unit tests? 
- I think you can remove the ERC721 implementation. See https://github.com/danforbes/pallet-nft  
- Do you already have a mock-up of the front-end, which you could share?

2021-01-08 02:46 UTC, bleemer4 commented
> Thanks for the application. It looks really interesting. I have a few questions:
> 
> * Could you also integrate unit tests?
> * I think you can remove the ERC721 implementation. See https://github.com/danforbes/pallet-nft
> * Do you already have a mock-up of the front-end, which you could share?

Thanks for your advice. We have added unit tests and removed ERC721 implementation in the application file.
And here is a link to show the MVP demo which we participated in a Substrate hackathon(mentioned in the application file) recently.
Vedio: https://drive.google.com/file/d/1fwOFVHOJxPBYL3hVIvXHRPAJFlgDaAxQ/view?usp=sharing
Mock-up of the front-end: https://drive.google.com/file/d/1gDZWCPIl5RRjOREdINRL4GbNONuXr_hd/view?usp=sharing

This version is very simple and in Chinese language, and we will continue to optimize  and internationalize it.
Many Thanks.

2021-01-08 10:39 UTC, rrtti commented
@bleemer4  Greetings! A group of devs, PMs and designers, along with artists and NFT creators are working on a **NFT strategy for Kusama network** (already ongoing: https://kusama.polkassembly.io/post/303). The effort includes the development of Asset creator platforms (RMRK.app and PolkadotAssetJS - funded by treasury) and the development and maintenance of two pallets to be natively deployed on Kusama: ORML NFT pallet and a PoC NFT Gallery to work as a first experimentation in the direction of a native application.   We would love to discuss your project to see how it could align with our efforts on this: let me know what you think!

2021-01-08 12:51 UTC, bleemer4 commented
> @bleemer4 Greetings! A group of devs, PMs and designers, along with artists and NFT creators are working on a **NFT strategy for Kusama network** (already ongoing: https://kusama.polkassembly.io/post/303). The effort includes the development of Asset creator platforms (RMRK.app and PolkadotAssetJS - funded by treasury) and the development and maintenance of two pallets to be natively deployed on Kusama: ORML NFT pallet and a PoC NFT Gallery to work as a first experimentation in the direction of a native application.   We would love to discuss your project to see how it could align with our efforts on this: let me know what you think!

Sounds cool. Very happy to hear that. Most our team members has AI related experience, and the original idea is to work well with AI training data(generation, swap, etc.).And we found NFT is a good way to describe data assets. We aim to make AI data worth to be spread and valued.
We're very glad to communicate with your team on NFT issues in the future.

2021-01-13 09:58 UTC, Noc2 requested changes
Thanks for the update and sorry for the late reply. In general, I’m happy with the application and willing to go ahead with it. But could you integrate the video and mockup into the application and also point out that the interface will be available in chinese as well as english. It would also be nice if you could publish an article as part of the grant.

2021-01-13 13:10 UTC, bleemer4 commented
> Thanks for the update and sorry for the late reply. In general, I’m happy with the application and willing to go ahead with it. But could you integrate the video and mockup into the application and also point out that the interface will be available in chinese as well as english. It would also be nice if you could publish an article as part of the grant.

Yep, we have updated the application file as you suggested.
Many thanks.

2021-01-13 13:27 UTC, Noc2 submitted a review, later dismissed
Looks good to me. I will share it with the rest of the team.

2021-01-14 13:54 UTC, mmagician commented
@bleemer4 Could you please provide an outline of what functionality is still missing from your [current implementation](https://github.com/DNFT-Team/dnft-substrate-node/tree/master/pallets/nft) that you're planning to develop as part of this grant?

2021-01-15 04:16 UTC, bleemer4 commented
> @bleemer4 Could you please provide an outline of what functionality is still missing from your [current implementation](https://github.com/DNFT-Team/dnft-substrate-node/tree/master/pallets/nft) that you're planning to develop as part of this grant?

Hi, @mmagician, thanks for your advice, we updated the application file and added an outline.

2021-01-15 10:39 UTC, mmagician approved these changes

2021-01-15 11:22 UTC, Noc2 approved these changes

2021-01-18 08:50 UTC, RouvenP approved these changes

2021-01-18 08:51 UTC, merged

2021-06-09 12:19 UTC, alxs commented
Hey @bleemer4. Care to share a quick status update on the project? Milestone 1 is by now delayed by 3 months and I can't see any implementation on your team's [repositories](https://github.com/DNFT-Team). Unless you're actively working on this, we will terminate the grant due to inactivity.

2021-06-09 12:36 UTC, bleemer4 commented
Hi,Aleixo
Sorry for&nbsp;delay.
The reason is we're working in a local env, considering for so many NFT projects.
We'll organize the chain code and commit in next two days.
We're changing the UI&amp;UX style,&nbsp; the full milestone1 will be committed in the next week.
Hoping our project will surprise you once we submit the full milestone1.
Sorry for delay again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w3f/Open-Grants-Program"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 晚上8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w3f/Open-Grants-Program] add DNFT (#188)





 
Hey @bleemer4. Care to share a quick status update on the project? Milestone 1 is by now delayed by 3 months and I can't see any implementation on your team's repositories. Unless you're actively working on this, we will terminate the grant due to inactivity.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-09 12:49 UTC, alxs commented
Sounds good @bleemer4, looking forward to the delivery.

2021-06-28 06:55 UTC, Noc2 commented
@bleemer4  It seems you still haven’t delivered any milestones. Furthermore you publicly claim everywhere that you received a grant from the web3, for example: 
- https://dnft.world/ 
- https://medium.com/dnft-protocol/we-want-you-b60f1dfeefb4
- https://cointelegraph.com/press-releases/web3-grant-project-dnft-protocol-connects-with-the-isolated-nft-world
- https://cryptoexploit.com/polkadot-web3-grant-project-dnft-is-connecting-the-isolated-nft-world/?utm_source=rss&utm_medium=rss&utm_campaign=polkadot-web3-grant-project-dnft-is-connecting-the-isolated-nft-world
- https://write.as/cryptoadventure/dnft-protocol-a-crypto-platform-aiming-to-revolutionize-nft 

You are only allowed to announce a grant, once you successfully delivered at least one milestone see [Announcement Guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/announcement-guidelines.md). Please clarify/update this. Also if you don’t deliver the milestone next week, we will highly likely terminate your grant.

2021-06-28 09:41 UTC, bleemer4 commented
Hi. David.
Sorry for delay, we have urgently deleted infos in the first two links, the others are third party article. We will pay attention in the publicity process.


The mileston1 will be committed in this week, as we checkout the list for millstone1 last week before we submit , we found some important docs missing.


Sorry for delay again.



---Original---
From: "David ***@***.***&gt;
Date: Mon, Jun 28, 2021 14:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [w3f/Open-Grants-Program] add DNFT (#188)




 
@bleemer4  It seems you still haven’t delivered any milestones. Furthermore you publicly claim everywhere that you received a grant from the web3, for example:
  
https://dnft.world/ 

https://medium.com/dnft-protocol/we-want-you-b60f1dfeefb4 

https://cointelegraph.com/press-releases/web3-grant-project-dnft-protocol-connects-with-the-isolated-nft-world 

https://cryptoexploit.com/polkadot-web3-grant-project-dnft-is-connecting-the-isolated-nft-world/?utm_source=rss&amp;utm_medium=rss&amp;utm_campaign=polkadot-web3-grant-project-dnft-is-connecting-the-isolated-nft-world 

https://write.as/cryptoadventure/dnft-protocol-a-crypto-platform-aiming-to-revolutionize-nft 
 
You are only allowed to announce a grant, once you successfully delivered at least one milestone see Announcement Guidelines. Please clarify/update this. Also if you don’t deliver the milestone next week, we will highly likely terminate your grant.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-05 09:59 UTC, borispoehland commented
@bleemer4 no milestone yet. Another deadline not met? 

@Noc2 their website dnft.world is completely removed. They also postponed their listing and held several IDOs (so collected funds) yet. If you ask me, and **ONLY** if you ask me, they could disappear with all the collected funds at this exact moment. In **MY** conspiracy theory they used the grants as a way to gain trust from their investors, to not let their project look like a scam

2021-07-05 10:19 UTC, FinQode commented
@Noc2 I appreciate the effort you have taken a week ago to remind the founder of DNFT of their obligations to deliver their milestones. I would also like to inform you that some of us (not me) have performed in depth research on the founder (with intelligence systems not available for the average person). The results of that research were very shocking.

I pray to God that for whatever reason our research results were wrong and that this project will deliver the promised milestones. We are all trying to make the cryptocurrency world a better place. A decentralized world that can be trusted. Unfortunately though we also have to acknowledge that there are people that abuse this.

Personally I have also have proof of communications with the founder asking me to commit fraud for a 'new project'. 

Perhaps all of that is not enough proof and perhaps we are looking at the best NFT cross-chain project here. May God be with us.

2021-07-05 10:29 UTC, bleemer4 commented
> @bleemer4 no milestone yet. Another deadline not met?
> 
> @Noc2 their website dnft.world is completely removed. They also postponed their listing and held several IDOs (so collected funds) yet. If you ask me, and **ONLY** if you ask me, they could disappear with all the collected funds at this exact moment. In **MY** conspiracy theory they used the grants as a way to gain trust from their investors, to not let their project look like a scam

Thanks for your attention, we have submitted the [millstone](https://github.com/w3f/Grant-Milestone-Delivery/pull/213) , we're constantly improving ourselves and learning from web3/substrate teams. Thanks for your advice.

2021-07-05 10:34 UTC, borispoehland commented
@bleemer4 why is dnft.world gone?

2021-07-05 10:44 UTC, bleemer4 commented
> @bleemer4 why is dnft.world gone?

We deleted the web3 info in our project website, in order to comply with the rules of Web3, and make up for our mistakes.
We're sorry for not understanding the rules before.
We made a quick adjustment when we knew it.
Sorry for not understanding the rules before @Noc2.

2021-07-05 10:48 UTC, borispoehland commented
@bleemer4 that was not my question. We noticed that you removed Web3 from your website a few days ago.

But now the website is completely gone. dnft.world is not reachable anymore. Please help me understand why that is

2021-07-05 11:07 UTC, bleemer4 commented
In the process of upgrading, maybe not stable.As part of our cross chain products is ready for testing,we update the website.

Thanks for attention.
Could you please post this kind of questions in our telegram or our other&nbsp;community tools.We will be happy to solve it for you.
Thanks for your attention again.



---Original---
From: "Boris ***@***.***&gt;
Date: Mon, Jul 5, 2021 18:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [w3f/Open-Grants-Program] add DNFT (#188)




 
@bleemer4 that was not my question. We noticed that you removed Web3 from your website a few days ago.
 
But now the website is completely gone. dnft.world is not reachable anymore. Please help me understand why that is
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-05 11:16 UTC, borispoehland commented
@bleemer4 on my computer I managed to call the site again. I think it's a caching issue then. I tried to delete my cache on my smartphone but it still doesn't work there. I don't know if you have to do something on your end. Maybe it's also because dnft.world is not SSL-encrypted right now (http instead of https)

2021-07-05 11:24 UTC, bleemer4 commented
Please have a&nbsp; try later, It's in upgrading.
Thanks for attention.



---Original---
From: "Boris ***@***.***&gt;
Date: Mon, Jul 5, 2021 19:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [w3f/Open-Grants-Program] add DNFT (#188)




 
@bleemer4 on my computer I managed to call the site again. I think it's a caching issue then. I tried to delete my cache on my smartphone but it still doesn't work there. I don't know if you have to do something on your end. Maybe it's also because dnft.world is not SSL-encrypted right now (http instead of https)
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-09-28 12:11 UTC, alxs commented
This grant has been [terminated](https://github.com/w3f/Grant-Milestone-Delivery/pull/213#issuecomment-918946371) due to inactivity.