Create nft908_protocol.md
w3f/Open-Grants-Program pull request #189
Opened 2021-01-07 15:47 UTC by dego-team

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

2021-01-07 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=189) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=189) it.</sub>

2021-01-08 10:39 UTC, rrtti commented
@dego-team Greetings! A group of devs, PMs and designers, along with artists and NFT creators are working on a **NFT strategy for Kusama network** (already ongoing: https://kusama.polkassembly.io/post/303). The effort includes the development of Asset creator platforms (RMRK.app and PolkadotAssetJS - funded by treasury) and the development and maintenance of two pallets to be natively deployed on Kusama: ORML NFT pallet and a PoC NFT Gallery to work as a first experimentation in the direction of a native application.   We would love to discuss your project to see how it could align with our efforts on this: let me know what you think!

2021-01-08 14:36 UTC, dego-team commented
@rrtti It is nice to hear back from you. I read about “NFT stragegy for Kusama network” related discussions and materials. They did a fantastic job and I am proud to be a part of it, seeing so many people contributing to Polka ecosystem.
That is more like realising ERC721. As described in our proposal, our ERC908 is compatible with ERC721 while it has more features to support more complex applications

2021-01-13 08:44 UTC, Noc2 requested changes
Thanks for the application. Sounds interesting. I have a few questions:
Why is it called NFT908? 

- In which programming language do you want to implement NFT908 and the App Demo. 
- Could you integrate the PSP process into your application: https://github.com/w3f/PSPs 
- Could you add documentation, license file and an article to the deliveries, see https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules

2021-01-13 14:38 UTC, dego-team commented
> * Why is it called NFT908?
908 means September 8. On that day, we finally discussed and determined the basic framework of the protocol.

> * In which programming language do you want to implement NFT908 and the App Demo.
NFT908 will going to be an substrate module。

> * Could you integrate the PSP process into your application: https://github.com/w3f/PSPs
No problem, let’s study it and submit a new PSP

> * Could you add documentation, license file and an article to the deliveries, see https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules

No problem, we will do it on  Milestone 2.

2021-01-13 14:38 UTC, dego-team commented
> Why is it called NFT908?
908 means September 8. On that day, we finally discussed and determined the basic framework of the protocol.

> In which programming language do you want to implement NFT908 and the App Demo.
NFT908 will going to be an substrate module。

> Could you integrate the PSP process into your application: https://github.com/w3f/PSPs
No problem, let’s study it and submit a new PSP

> Could you add documentation, license file and an article to the deliveries, see https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules
No problem, we will do it on Milestone 2.

2021-01-15 09:48 UTC, Noc2 commented
Could you integrate the psp proposal into the application? Also do you have more information about why this new NFT standard is necessary. I saw you also started to work on https://github.com/dego-labs/erc908/blob/main/EIP-908.md. Are you aware that [EIP-908](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-908.md) already exists and that the number is usually based on the PR number.

2021-01-22 18:11 UTC, dego-team commented
Sorry, I want to submit this grants after we complete the test and submission of the EIP protocol. Sorry for causing you trouble

2021-01-22 18:12 UTC, closed without merging