Create polkakeeper.md
w3f/Open-Grants-Program pull request #200
Opened 2021-01-14 10:32 UTC by RAMPDEFITEAM

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-14 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=200) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=200) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=200) it.</sub>

2021-01-14 11:39 UTC, Noc2 requested changes
Thanks for the application. In general this sounds interesting. However, it might be a little bit early for this kind of application in our ecosystem or do you have already specific “jobs” in mind. Did you already play around with ink!, substrate or rust and have some code which you could share?

2021-01-14 19:07 UTC, semuelle reviewed
Some minor questions from me:

2021-01-15 09:19 UTC, RAMPDEFITEAM commented on applications/polkakeeper.md
> +Upon successful Keeper execution, the protocol takes 3.5% of the profits, and the remaining is distributed among the Strategist, Finder and Vaults. Where funds or assets in Vaults are not utilized, t
A small fee is taken for the maintenance and upgrading of the substrate components utilized. Would edit that in the new pull request

2021-01-15 09:20 UTC, RAMPDEFITEAM commented on applications/polkakeeper.md
> +* Registered Address: 14 ROBINSON ROAD #08-01A FAR EAST FINANCE BUILDING S(048545)
Added, would be reflected in the new pull request

2021-01-15 09:22 UTC, RAMPDEFITEAM commented on applications/polkakeeper.md
> +| 1. | Testing | We will conduct testing of the developed functionalities on Rococo testnet |
Deliverables would be definitive. Would be reflected in the new pull request.

2021-01-19 05:32 UTC, RAMPDEFITEAM commented
> Thanks for the application. In general this sounds interesting. However, it might be a little bit early for this kind of application in our ecosystem or do you have already specific “jobs” in mind. Did you already play around with ink!, substrate or rust and have some code which you could share?

Yes, we believe that for each blockchain in the Defi space, there needs to be proper infrastructure in place as growth of the eco-system develops. Hence we are building up important lego pieces for Vault and Liquidation functionality that can be called to manage the risk within projects. Our developers have the foundational level understanding of substrate and rust and are deep diving in research to develop this project. We have updated our PR to reflect specifically the Vault and Liquidation funcationality.

2021-01-19 14:32 UTC, Noc2 requested changes
Thanks for the update. Makes sense. Regarding the Technical Milestones, could you restructure these? We generally focus on the development of open source software, which can potentially be reused by others in the ecosystem. So, we wouldn’t support the integration into the parachain or testing as part of the roco integration. Instead we would rather have the concrete open source deliveries as part of the delivery table, e.g. runtime module, ui etc. plus the specification of these (e.g. functions, programing language, etc.).

2021-01-20 15:34 UTC, RAMPDEFITEAM commented
> Thanks for the update. Makes sense. Regarding the Technical Milestones, could you restructure these? We generally focus on the development of open source software, which can potentially be reused by others in the ecosystem. So, we wouldn’t support the integration into the parachain or testing as part of the roco integration. Instead we would rather have the concrete open source deliveries as part of the delivery table, e.g. runtime module, ui etc. plus the specification of these (e.g. functions, programing language, etc.).

@Noc2 : Restructured the Technical Milestones to make it more concrete with clear open source deliveries of reusable components in each milestone. Included also a Technical Stack Specification for clarity.

2021-01-21 09:54 UTC, Noc2 requested changes
Thanks for the update, but now your milestones no longer have a payment associated with them. So does your complete project consist of a single milestone? Also milestone one says only “the pallets” without specifying which pallets.

2021-01-21 10:31 UTC, RAMPDEFITEAM commented
> Thanks for the update, but now your milestones no longer have a payment associated with them. So does your complete project consist of a single milestone? Also milestone one says only “the pallets” without specifying which pallets.

@Noc2 We have updated our PR to reflect the individual Milestone payments attached to each Milestone. There are a total of 3 milestones stated for this project. The Pallets refer to the Vault, Liquidator and LiquidatorAdaptor Pallets as described.

2021-01-26 12:58 UTC, Noc2 requested changes
Sorry for the late reply and thanks for the update. I have a two additional comments/questions:

- Could you also integrate the license into the deliveries 2 and 3? 
- What is the difference between milestone 1, 2 and 3? It’s currently very difficult for us to evaluate the deliveries. For example what features will the finished ui support, which aren’t already implemented as part of milestone 2. The same is true for the pallets. Could you be more specific about the functionality of the different delivieries?
- Also it would be nice to have a good unit test coverage for milestone 3.

2021-01-27 07:53 UTC, RAMPDEFITEAM commented
> Sorry for the late reply and thanks for the update. I have a two additional comments/questions:
> 
> * Could you also integrate the license into the deliveries 2 and 3?
> * What is the difference between milestone 1, 2 and 3? It’s currently very difficult for us to evaluate the deliveries. For example what features will the finished ui support, which aren’t already implemented as part of milestone 2. The same is true for the pallets. Could you be more specific about the functionality of the different delivieries?
> * Also it would be nice to have a good unit test coverage for milestone 3.

@Noc2 
- Integrated licensing for Milestones 2 and 3.
- UI Development Goals have been specified and stated
- Milestone 2 UI would be completed but functionality integration to real-world chain yet to be done. Milestone 3 UI would be completed AND functionality integration to real-world chain done.
- Pallets have been specified and include (liquidation, borrowing).
- Milestone 2 Pallets unit test would be basic <30% coverage
- Milestone 3 Pallets unit test would be 85% coverage

2021-01-27 09:36 UTC, Noc2 commented
Thanks again for the quick response and update. @coostendorp still needs to sign the CLA, once this is done, please ping me and I will share it with the rest of the team.

2021-01-27 10:33 UTC, RAMPDEFITEAM commented
> Thanks again for the quick response and update. @coostendorp still needs to sign the CLA, once this is done, please ping me and I will share it with the rest of the team.

Hey @Noc2 , thanks for the quick reply. @coostendorp has signed the CLA too. Thanks!

2021-01-28 15:22 UTC, Noc2 submitted a review, later dismissed
Thanks. I will share it with the rest of the team.

2021-01-29 09:36 UTC, RouvenP approved these changes

2021-01-30 14:49 UTC, RAMPDEFITEAM commented
> Thanks. I will share it with the rest of the team.

Thanks @Noc2

2021-01-30 17:54 UTC, RAMPDEFITEAM commented
> Some minor questions from me:

Hey @semuelle , PR has been updated since. Thanks!

2021-02-01 11:26 UTC, mmagician requested changes
As per the above comments, I would be reluctant to fund M1, which would result only in placeholders that don't contribute much, in my opinion.

2021-02-01 11:26 UTC, mmagician commented on applications/polkakeeper.md
> +| Source code| Vault, Liquidator and LiquidatorAdaptor pallets all implemented with basic (<30%) unit test coverage.|
Could you outline the difference in functionality between Milestone 2 and 3, apart from unit test coverage? Will the solution be feature-complete by the end of M2?

2021-02-01 11:26 UTC, mmagician commented on applications/polkakeeper.md
> +#### Milestone 1: Preparation (0.10 BTC)
I don't see any concrete benefit of M1 as a standalone delivery, since the code that you propose to develop (pallet outlines & substrate node template) is readily available from official substrate repos & unless I am missing something, the only thing to be done here is replacing placeholders with the names of your pallets.

Furthermore, design specifications are expected to be part of the grant application and as such, are not explicitly funded.

2021-02-02 03:52 UTC, RAMPDEFITEAM commented on applications/polkakeeper.md
> +| Source code| Vault, Liquidator and LiquidatorAdaptor pallets all implemented with basic (<30%) unit test coverage.|
@mmagician besides the unit test coverage, the other key difference between milestone 2 and 3 is that milestone 2 would be feature complete for internal use but would not yet be connected to a real chain for general use whereas milestone 3 would be connected to a real chain and ready for general public use.

2021-02-02 03:56 UTC, RAMPDEFITEAM commented on applications/polkakeeper.md
> +#### Milestone 1: Preparation (0.10 BTC)
@mmagician we have collapsed milestone 1 & milestone 2 together and adjusted the milestone payout. There are now only 2 milestones with milestone 1 being feature-complete for internal use (working internal POC not connected to a real chain) and milestone 2 being ready for general use (fully functional and compatible with real chain) by the public.

2021-02-02 17:13 UTC, RAMPDEFITEAM commented
@Noc2 @RouvenP , apologies, the review was accidentally dismissed. Could you kindly approve the review again pls. Thanks!

2021-02-02 19:23 UTC, Noc2 approved these changes

2021-02-03 08:31 UTC, mmagician approved these changes
Alright, thanks for the updates and good luck with the development!

2021-02-03 08:34 UTC, RouvenP approved these changes

2021-02-03 08:37 UTC, merged

2021-02-03 10:30 UTC, RAMPDEFITEAM commented
Thank you @Noc2 @RouvenP @mmagician ! Our team is excited to be able to contribute :)

2021-05-24 07:53 UTC, RAMPDEFITEAM commented
Hi @Noc2 @mmagician @RouvenP, we've been working on our pallets but having some trouble compiling due to substrate bug. We've had help from 2 support engineers but have still not been able to get things working.

Would you be able to guide us technically or point us in the correct direction? Here's the link to detail out the error and issue.

https://docs.google.com/document/d/1e6GuwP7fvgJK1VYaZ_gJ4DtPfXuMd8lmAI7RRvEV4h8/edit?usp=sharing

Appreciate any help!

2021-05-28 10:55 UTC, alxs commented
Hi @RAMPDEFITEAM. Unfortuately we don't usually provide technical support in the context of the grants program (see [README](https://github.com/w3f/Open-Grants-Program#support)). Besides, I'm afraid if two Parity engineers haven't been able to help, chances are neither will we. You'll have better chances of getting an answer on one of the resources listed [here](https://substrate.dev/en/community), in particular the Substrate Technical Element chat or Stack Overflow.

I hope you can resolve the issue soon, but do let us know if you're out of options and we'll see what we can do.

2021-05-28 18:17 UTC, RAMPDEFITEAM commented
Hi Aleixo,

Thanks for your reply.

Would try those and if it doesn't work will reach out again.

Cheers!
RAMP DEFI TEAM

On Fri, 28 May 2021 at 18:55, Aleixo Sánchez ***@***.***>
wrote:

> Hi @RAMPDEFITEAM <https://github.com/RAMPDEFITEAM>. Unfortuately we don't
> usually provide technical support in the context of the grants program (see
> README <https://github.com/w3f/Open-Grants-Program#support>). Besides,
> I'm afraid if two Parity engineers haven't been able to help, chances are
> neither will we. You'll have better chances of getting an answer on one of
> the resources listed here <https://substrate.dev/en/community>, in
> particular the Substrate Technical Element chat or Stack Overflow.
>
> I hope you can resolve the issue soon, but do let us know if you're out of
> options and we'll see what we can do.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3f/Open-Grants-Program/pull/200#issuecomment-850334306>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ2JKTZ255WMUCADCV3WDB3TP5ZBTANCNFSM4WCG4DUA>
> .
>

2021-07-29 13:29 UTC, alxs commented
@RAMPDEFITEAM I hope you managed to get past those issues. Unless you're planning to deliver milestone 1 in the near future, could you please submit an amendment to your application to update the duration or include an ETA?

2021-08-12 09:41 UTC, alxs commented
Quick heads-up that since we haven't heard from you in a while and there's no significant activity on your public [repositories](https://github.com/RAMP-DEFI), we would terminate the grant in the coming days. If you're still interested in delivering 1 in the foreseeable future, please briefly let us know.