Create ZeroPool.md
w3f/Open-Grants-Program pull request #208
Opened 2021-01-18 20:28 UTC by snjax

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-18 20:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=208) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=208) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=208) it.</sub>

2021-01-19 08:14 UTC, Noc2 requested changes
Thanks for the applications. A few questions from my side (also based on some internal feedback): 

- You still need to sign the Terms and conditions.
- Could you try to leverage the [open grants template for the application](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#development-roadmap-nut_and_bolt). Specifically regarding the milestones.
- Has ZeroPool received any funding/further support from the Ethereum Foundation to develop their research?
- The application is pretty ethereum focused. "ZeroPool supports ERC20 and ERC721". Are there any adjustments planned for Polkadot?
- Has any of the ZeroPool (ethereum) code been audited so far?

2021-01-22 19:27 UTC, burdges commented
What is the ZeroPool design?  Zcash-like?  Spends reference UTXOs via a Merkle tree.  And nullifiers accumulate?  That'd be fine.  

Any cryptography could run in WASM on substrate of course, but..

We'll eventually provide native code support for BLS12-377, BW6, and their JubJubs via Arkworks.  If you're interested in helping there then take a look at https://github.com/arkworks-rs/curves/issues/17 

We'll probably never provide any native code support for any non-arkworks curves implementations besides our existing secp256k1 and ed25519/ristretto code.

2021-01-25 13:25 UTC, snjax commented
@burdges,

>What is the ZeroPool design? Zcash-like? Spends reference UTXOs via a Merkle tree. And nullifiers accumulate on-chain? That'd be fine.

It is like ZCash, but there are some differences for better support of account-based chains. For example, with such privacy as ZCash we publish only one nullifier per transaction. So, storage space is used more sparingly.

[My talk on ZKSummit about account-based privacy](https://www.youtube.com/watch?v=f885LTdgJVs)
[Account-based private transaction engine](https://ethereum-magicians.org/t/account-based-private-transaction-engine/4833)

> Any cryptography could run in WASM on substrate of course, but.

Our current plans are building protocol at the most widespread curve and proving system (currently it is groth16 and bn256). With the current codebase, we can deploy the working solution faster and safer.

After that, we are going to switch our research to more novel protocols. 1-level recursion on BLS12-377 and BW6 is promising. But novel protocols could be better.

2021-01-25 14:17 UTC, burdges commented
We've no timeframe for doing anything native, so yes if your code works well in WASM then that'll definitely be faster, and sure bn254 might run faster in WASM than BLS12-377 or whatever.  I mentioned https://github.com/arkworks-rs/curves/issues/17 largely because it might fit your team's interest.

2021-01-28 11:13 UTC, burdges commented
Apologies for the delay.. Yes, we should fund this project @Noc2 

@snjax  As you're doing zk, you could do you own off-chain storage likely just block contents aka UTXOs, but also you could use Poseidon integrated with substrate's storage in your own substrate fork, and then only provide SNARKs that get checked in the runtime (eventually on polkadot).  I'd think either of the top contributors to https://github.com/paritytech/trie/graphs/contributors could give advise on this if you need anything like that.  We're quite slow about upstreaming improvements to substrate's storage architecture, but we'd love to see exploration of such options.

2021-01-28 11:29 UTC, burdges commented
I'm confused by one point, what do you mean by "optimistic rollup"?

2021-01-29 01:23 UTC, snjax commented
@burdges,

>what do you mean by "optimistic rollup"?

Our current beta implementation on Ethereum is working on L2 (custom optimistic rollup). In optimistic rollup, the relayer just publishes transactions and result of VM execution, but do not execute them. If the result is wrong, anybody can challenge the relayer by executing the transaction and stop the rollup. So, an expensive zkSNARK verifier is executed only if the relayer publishes damaged data.

>if I understand, users supply SNARKs for UTXOs but you'll support accounts too?

Yes, the account is a special type of UTXO, containing spend interval (in the simplest case it is maximal UTXO index spendable by the user). So, when we perform the transfer, it is enough only to publish only one nullifier for an account and increase the spent interval for the account.

>you could use Poseidon integrated with substrate's storage in your own substrate fork, and then only provide SNARKs that get checked in the runtime (eventually on polkadot)

Sure, we are going to compute Poseidon only off-chain and verify Merkle root update with zkSNARKs. Poseidon is very expensive to compute it onchain.

2021-01-29 15:18 UTC, Noc2 commented
@snjax would it be possible to reduce the price. This way it will be easier to get the necessary approval.

2021-02-03 17:25 UTC, snjax commented
> 
> 
> @snjax would it be possible to reduce the price. This way it will be easier to get the necessary approval.

@Noc2, now we can reduce the total amount by removing the last milestone. Also, we start thinking about publishing our SDK, so other developers could implement their own dApps, based on our protocol.

2021-02-04 12:31 UTC, Noc2 commented
@snjax Thanks for updating the application. Removing the last milestone makes a lot of sense. Especially since we can always sign a follow-up grant for it, but I was more referring to the general costs of the proposal. For example Milestone 2 and 3 both currently have the same estimated duration and FTE and milestone 2 costs 40k instead of 30k. It would be appreciated if you could reduce the price of the deliveries a little bit more and would help to get the necessary approval from the rest of the committee.

2021-02-23 09:58 UTC, Noc2 commented
@snjax Any updates on this?

2021-02-23 18:23 UTC, snjax commented
@Noc2 
We very much appreciate the cooperation with you and the work we have done. I think we are able to consider 63k dai as a total grant amount for current milestones.

The costs are different because each step requires different people.

2021-02-23 19:47 UTC, Noc2 commented
@snjax Thanks for the quick response. Sounds good to me. Could you update the application?

2021-02-23 21:01 UTC, snjax commented
@Noc2  done

2021-02-24 08:23 UTC, Noc2 approved these changes
Thanks for the update. I’m happy to go ahead with it and I will share the application with the rest of the committee.

2021-02-24 11:23 UTC, mmagician approved these changes
The previous delivery was good, I'm also happy to proceed with a follow-up

2021-03-01 22:17 UTC, BenWhiteJam approved these changes

2021-03-02 08:05 UTC, merged

2021-06-09 13:43 UTC, alxs commented
Hey @snjax, care to share a quick status update on the project?

2021-06-11 19:57 UTC, snjax commented
Hi, @alxs. Now we are focused on the core part of development (cryptography, zkSNARKs, and documentation). We decided to go step by step. Now we prepared zkSNARKs for the audit.
So, we could be sure, we reduce the security risks as more as we can before the release. And further development is going to be more smooth and more effective.

2021-06-12 12:11 UTC, alxs commented
Thanks for the update, sounds like a wise decision. If you expect M2 to still take a while, I recommend you submit an amendment and modify its duration accordingly.

2021-07-22 15:51 UTC, semuelle commented
It sounds like it might still take some time before you can submit a milestone, @snjax. Could you submit a PR to your grant application with an updated timeline?

2021-08-03 11:49 UTC, alxs commented on applications/ZeroPool.md
> +* **Estimated Duration:** 2 months
Please @snjax, submit an amendment. The duration should be updated to 5 months (which would be now) + however long you think you will still need.

2021-10-05 19:19 UTC, alxs commented
@snjax this is a last request to please submit an amendment. Otherwise, we'll terminate the grant in the coming days.

2021-11-29 16:43 UTC, alxs commented
@snjax a reminder to submit milestone 2 - please follow the process above.

2021-12-03 01:01 UTC, snjax commented
@alxs Sorry for the late reply, it was LisCon and big backlog. I submitted the milestone 2 here https://github.com/w3f/Grant-Milestone-Delivery/pull/316