Create MIXER.md
w3f/Open-Grants-Program pull request #216
Opened 2021-01-22 02:57 UTC by drewstone

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-22 02:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=216) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=216) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=216) it.</sub>

2021-01-22 09:42 UTC, mmagician requested changes
@drewstone Thanks for the application, it looks interesting. Bear in mind that the 100k limit only applies to verified teams which have already delivered another w3f grant, otherwise the limit is 30k. 

My suggestion is to therefore apply only with the first milestone. I believe that his should be a good enough PoC demonstrating the mixer's functionality & if successful, then you can proceed with the subsequent milestones.

Also I would suggest that the points from notion relevant to M1 be integrated into the application itself and listed under milestone deliverables.

2021-01-22 18:07 UTC, drewstone commented
ok, will remove all but the first milestone!

2021-01-22 18:28 UTC, drewstone commented
@mmagician thanks for the notes, I just updated the document with only the 1st milestone and all relevant tasks/specs on those portions.

2021-01-29 21:20 UTC, mmagician commented
@drewstone Thanks for applying the suggestions. I've shared the application with our researchers to get their feedback.

2021-01-29 22:43 UTC, burdges commented
As a rule, mixers provide almost no privacy, which makes me reluctant to endorse anything like that.

Just fyi, we've this idea that mimblewimble coupled with sassafras provides far more privacy than grin.mw could ever deliver, but deploying sassafras requires considerable work still, then we've more work to deprecate all mempools, and only once the mempools die does mimblewimble make sense.

2021-01-31 22:48 UTC, drewstone commented
> As a rule, mixers provide almost no privacy, which makes me reluctant to endorse anything like that.

Can you speak more to this @burdges? I'm under the impression that with a large enough anonymity set we can have measurable privacy.

Also if I may, these primitives could be useful for more than just mixing as the proofs we want to build support merkle tree membership proofs in zero-knowledge. This can be seen as an adapted grant from https://github.com/w3f/General-Grants-Program/pull/168 which provides similar primitives, just now using Curve25519/Bulletproofs.

2021-02-11 08:02 UTC, mmagician commented
@burdges do you have any further comments or reservations, or would you be OK to give this project a shot?

2021-02-24 18:49 UTC, drewstone commented
I'm confused, the previous grant was reopened though the tech is quite similar. Is there an interest in funding this?

2021-02-25 08:46 UTC, Noc2 approved these changes
Alex recently joined us and just tried to clean up old PRs of the general grants repo. So it’s unrelated to the discussion here. 

I would be willing to just go ahead with this project and give it a try. Even if it doesn’t provide perfect privacy, it might be still better for some use cases/projects in our ecosystem.

2021-02-25 10:32 UTC, burdges commented
I think the more focused upon more generically useful stuff the better, another related goal might be some mimblewimble like design.  Improving substrate support for zk friendly Merkle trees helps.

2021-02-25 11:34 UTC, mmagician commented
One last question from my side (on behalf of another researcher): could you perhaps outline any similarities and differences between your solution and tornado cash?

2021-02-25 17:13 UTC, drewstone commented
The pallet will be quite general to other use cases and supports general group creation in a merkle tree.

@mmagician similarities between this and tornado are around functionality, they are quite similar. Different here is that we use non-trusted setup SNARKs (bulletproofs for now) and support Curve25519 directly. Differences beyond the mixer are supported arbitrary group / tree creation for other use cases.

2021-02-26 11:15 UTC, mmagician approved these changes

2021-03-01 13:56 UTC, semuelle commented
Hey @drewstone, could you also move the project description and any other relevant information that's in the Notion doc and not in your .md into this PR? We have to be able to go back to your project proposal for evaluation, so we rather not rely on documents hosted elsewhere.

2021-03-02 09:59 UTC, drewstone commented
@semuelle all the notes from the notion doc are in the readme document and there are extras afaik in the beginning.

2021-03-02 10:04 UTC, semuelle approved these changes
lgtm

2021-03-02 10:05 UTC, merged