Add Treasureland Grant
w3f/Open-Grants-Program pull request #218
Opened 2021-01-22 18:17 UTC by dego-team

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-27 14:39 UTC, Noc2 requested changes
Thanks for the new application. However, we would not fund the development of a Pallet_nft_721	at this stage given that there are already existing implementations (See for example https://github.com/danforbes/pallet-nft). Also the following team is already planning to work on something similar, including the ERC1155 implementation. How is your solution different from their solution: https://github.com/w3f/Open-Grants-Program/pull/188? What exactly would you integrate as part of the front end and why did you decide against the implementation of solidity smart contracts as you originally planned (see #198)?

2021-01-28 14:23 UTC, dego-team commented
Hi, thanks for your reply. 

I'm happy to learn other team's work in the NFT field. The core of our Treasureland lies in the trading, auctioning and other features, not in the implementation of the protocol itself. We will look into those two projects you mentioned, if they are highly available, then we will spare our efforts on the implementation of nft_721 and nft_1155.

Treasureland is already the largest market for NFT on BSC by transactions. Given the prosperity of Polka ecosystem, our next goal is to be the largest NFT market in Polka too. If we implement using Solidity Contracts only, then those NFTs generated based on Substrate, would fail to enter our market, which is something we don't want to see. So, we replaced the implementation.

2021-02-02 15:03 UTC, Noc2 requested changes
Thanks for updating the proposal. I have two follow-up questions: Could you specify the front-end part a little bit better. I’m not sure if I already asked this question before, but do you already have some mock-ups? In which programming languages are you planning to implement the front-end and which functionality will it support? https://www.treasureland.market/ doesn’t seem to load for me. Regarding milestone 2, is this only about the API or is this also related to the front-end, e.g. NFT information browsing and enquiry? And could you integrate unit tests for milestone 2 into the application?

2021-02-03 07:00 UTC, dego-team commented
Thanks for your replay.
Our front end uses the React framework. We support NFT display, sale, auction, minting and other modules, which are also added to grant application. https://www.treasureland.market/ # / home This is currently supported by bsc wallet by default. See screenshot:
[https://github.com/treasureland-market/doc/blob/main/treasureland-nft-list.png](https://github.com/treasureland-market/doc/blob/main/treasureland-nft-list.png)

This is one of our NFT list, showing the sale section, this is the ticket/souvenir NFT we are commissioned to make for Binance Blockchain Week. We provided dev. support for the event and made a Dapp called ScanDrop. See here: 
[https://www.binance.com/en/blog/421499824684901559/Watch-Binance-Blockchain-Week-for-the-Chance-to-Win-Limited-Edition-NFTs](https://www.binance.com/en/blog/421499824684901559/Watch-Binance-Blockchain-Week-for-the-Chance-to-Win-Limited-Edition-NFTs)

Milestone2 is primarily for upgrading APIs and this does not include the front end. Our API on the BSC is quite complete, see: 
[https://api.dego.finance/graph/subgraphs/name/Dego/market/graphql](https://api.dego.finance/graph/subgraphs/name/Dego/market/graphql)

2021-02-09 16:24 UTC, Noc2 requested changes
Sorry for the late reply. Thanks for the update. Could you initially remove the second milestone and just focus on the first milestone and also add more details to the deliveries (e.g. programming languages rust + react, clarify that you develop substrate pallets). I think this way it will be easier to accept for the rest of the committee.

2021-02-09 16:25 UTC, Noc2 commented
Btw. there is a new [Element](https://app.element.io/#/room/#web3nft:web3.foundation)/[Telegram](http://t.me/rmrkapp) chat group for all things NFT on Kusama and Polkadot. Also something you should be aware is that: A group of devs, PMs and designers, along with artists and NFT creators are working on a NFT strategy for Kusama network (already ongoing: https://kusama.polkassembly.io/post/303). The effort includes the development of Asset creator platforms (RMRK.app and PolkadotAssetJS - funded by treasury) and the development and maintenance of two pallets to be natively deployed on Kusama: ORML NFT pallet and a PoC NFT Gallery to work as a first experimentation in the direction of a native application. If you have any questions regarding this feel free to contact https://github.com/rrtti

2021-02-10 07:34 UTC, Noc2 commented
And just an additional note: I and my colleagues have a lot of issues with https://www.treasureland.market/ (e.g. it doesn’t load or even with metamask activited you can not see the items, which I think is quite bad from a UI perspective).

2021-02-10 16:13 UTC, dego-team commented
> Sorry for the late reply. Thanks for the update. Could you initially remove the second milestone and just focus on the first milestone and also add more details to the deliveries (e.g. programming languages rust + react, clarify that you develop substrate pallets). I think this way it will be easier to accept for the rest of the committee.

Thank you for giving me more information about NFT on Kusama and Polkadot. I have joined the Telegram Chat Group and will keep an eye on the information. In addition, i have updated grant application as you suggested. Looking forward to hearing from you. Thank you.

2021-02-10 16:17 UTC, dego-team commented
> And just an additional note: I and my colleagues have a lot of issues with https://www.treasureland.market/ (e.g. it doesn’t load or even with metamask activited you can not see the items, which I think is quite bad from a UI perspective).

Sorry i forgot to remind you。 We are built on the BSC network by default. You need to add the configuration of the BSC network. For details, please refer to:
https://docs.binance.org/smart-chain/wallet/metamask.html

However, this experience is really not very friendly at present, we will increase the optimization of network reminders later。Thank you for your feedback

2021-02-11 08:31 UTC, Noc2 approved these changes
Thanks for the update.

2021-02-11 08:34 UTC, Noc2 requested changes
Sorry, I have one more request: Could you add support for the [polkadot-js extension](https://github.com/polkadot-js/extension) to the UI. You probably have to do it anyway otherwise the UI will not be very user friendly.

2021-02-12 02:11 UTC, dego-team commented
> [polkadot-js extension](https://github.com/polkadot-js/extension)

Thank you, very good suggestion, we will support it

2021-02-12 08:31 UTC, Noc2 approved these changes
Thanks again for the update. I’m willing to go ahead with it and will share the application with the rest of the team.

2021-02-12 16:27 UTC, dego-team commented
> Thanks again for the update. I’m willing to go ahead with it and will share the application with the rest of the team.

Thanks, I am very happy to communicate with you.  I am looking forward to your reply.

2021-02-25 06:55 UTC, dego-team commented
> Thanks again for the update. I’m willing to go ahead with it and will share the application with the rest of the team.

@Noc2 Hi,  any update?

2021-02-25 07:33 UTC, Noc2 commented
Hi. It doesn’t look like the rest of the committee is interested in the application, but I will ping them again. Sorry for the delay.

2021-02-26 10:20 UTC, dego-team commented
> Hi. It doesn’t look like the rest of the committee is interested in the application, but I will ping them again. Sorry for the delay.

Thanks for your support. I am looking forward to your message.

2021-03-03 17:20 UTC, semuelle approved these changes

2021-03-08 19:59 UTC, alxs commented
Hi @dego-team. I'm unsure about this as your application is a bit scarce, but I'm interested. Would you care to add some technical details as well as more concrete future plans? Specifically with regards to the pallets that you plan to implement. Do you plan to deploy these anywhere or will you just make them available to the community? How can they be used besides through your platform? Also can you confirm that support for NFT721 and NFT1155 and only those is part of the milestone.

Lastly, do you have any reactions from the community to your plans that you could share?

2021-03-15 16:40 UTC, mmagician approved these changes
I'd be happy to give it a try. Good luck!

2021-03-15 16:40 UTC, merged

2021-07-05 18:03 UTC, alxs commented
Hi @dego-team. Are you still interested in this grant? Your repositories look inactive and the delivery is overdue - unless you're actively working on the project, we will terminate the agreement in the coming days.

2021-07-19 13:47 UTC, alxs commented
This grant is being terminated due to inactivity. Feel free to apply again if you're still interested.