Signal app is compatible with polkadot's private key system
w3f/Open-Grants-Program pull request #220
Opened 2021-01-24 11:37 UTC by Signaldot

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-24 11:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=220) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=220) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=220) it.</sub>

2021-01-26 13:54 UTC, semuelle commented
Hi @Signaldot, thank you for your submission. This overlap might indeed be a good opportunity. We would need a few more details in your proposal, though. Specifically:

- previous experience and work you have done on this project or related projects,
- more details on the technical deliverable(s), such as its intended use, interfaces being implemented or exemplary projects,
- documentation of the deliverables (our [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules) lists some examples)

Also, your milestone name is `Implement Substrate Modules`, and your deliverable is `singal app ed25519 private key system compatible`. Please specify what exactly you want to implement, and how and where it fits into the Polkadot ecosystem.

2021-01-26 13:56 UTC, semuelle requested changes
see comment above

2021-02-01 06:25 UTC, Signaldot commented
Thank you for your reminder, the document has been updated, adding many details in these areas

2021-02-25 18:20 UTC, semuelle commented
Hi @Signaldot,
thank you for the write-up about Signal and the added information. However, for this to be a convincing grant application would require additional details.

- You have to provide information on how exactly Polkadot and Signal are compatible (links to implementations of cryptographic algorithms, academic publications on the matter, etc.) and why Signal (other than being a good product in itself) lends itself to adaptation to Substrate. 
- You have to show previous experience with Rust, cryptography, mobile client development and Substrate (or at least a subset of these), ideally by providing links to public repositories;
- You have to significantly expand the `What we are doing` section of your application. The project overview is 90% describing the state of the art and less than 10% planning.
- Be more specific with what you are trying to accomplish. "communication suitable for the blockchain field" and "increase the binding and mapping of the substrate ecological private key system" are too vague. 
- If you make sweeping statements like "It is known as the most secure communication protocol in the world", please provide sources for these claims.

If you can show the previous experience that would be required, I would recommend to reduce this grant to a minimal proof-of-concept and, if successful, to apply for a follow-up grant to build the client integration, UIs and a fully-featured library.

2021-03-12 11:08 UTC, alxs commented
Closing due to inactivity. Feel free to leave a comment when you've put together a more detailed application as per @semuelle's suggestions and we'll reopen the PR.

2021-03-12 11:08 UTC, closed without merging