quadratic-funding
w3f/Open-Grants-Program pull request #227
Opened 2021-01-27 17:45 UTC by zhangjiannan

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-28 14:15 UTC, Noc2 requested changes
Thanks for the application. We are indeed interested in this at the moment, see https://github.com/w3f/General-Grants-Program/blob/master/rfp-proposal/on-chain-quadratic-funding.md and recently also received a similiar application: https://github.com/w3f/General-Grants-Program/pull/381 But at this price point it make sense to support your project as well. Could you maybe also integrate a license file and unit tests according to the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md for each delivery).

2021-01-28 18:28 UTC, zhangjiannan commented
Hi @Noc2 thank you so much for your quick response and feedback. I just pushed the changes. I also checked out your application, I think it's interesting to try MACI and Sybil resistance mechanisms. We would love to have further discussion with you on these topics later while we work on the pallet of this application.

2021-01-29 08:42 UTC, Noc2 approved these changes
Thanks. I will share it with the rest of the team.

2021-01-29 08:49 UTC, mmagician approved these changes

2021-01-29 09:31 UTC, RouvenP approved these changes

2021-01-29 09:31 UTC, merged