Remote Signing and Slashing Protection
w3f/Open-Grants-Program pull request #230
Opened 2021-01-28 13:05 UTC by skardas

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-28 13:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=230) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=230) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=230) it.</sub>

2021-01-28 13:09 UTC, skardas reviewed
ok

2021-01-28 13:54 UTC, fruit37 approved these changes

2021-01-28 14:50 UTC, mehmetankr approved these changes

2021-01-28 17:36 UTC, dmitry123 approved these changes

2021-01-29 08:47 UTC, mmagician requested changes
@skardas Thanks for the application, I think remote signing could be a good addition to the operation of validators. However, I have a few comments:

1. Approving your own PR doesn't help, only authorised users' approvals count
2. We don't fund the design & specification phase - this should comprise part of your initial research into the technology and should be submitted as part of the application itself. Furthermore, having developed a similar mechanism for eth already, it sounds like you should be able to provide a detailed architecture overview already.
3. > Providing a crypto library that supports ECDSA, Ed25519, and sr25519 signature algorithms

These libraries already exist. Could you outline what exactly is your contribution here?

4. > To add slashing prevention we also need to pass payload details into backend. 

How is this going to prevent slashing? Could you outline how the backend is going to process/store this information in order to prevent slashing?

5. > However, it should also be implemented in Polkadot codebase directly (i.e., not in Substrate).

Please elaborate on this point, as it's not entirely clear what you mean here.

6. > Providing a remote server

It's alright that you run a server yourself, but what we require for the Grants Program is to have the code open sourced, so that users can, if they choose, run such a server themselves. Are you fine with doing this?

To summarise, I think the grant could potentially make an impact on how validators process tx's, but please review the above points before we consider the application further.

2021-02-01 22:42 UTC, mmagician commented
Closing in favour of https://github.com/w3f/Open-Grants-Program/pull/237

2021-02-01 22:42 UTC, closed without merging