Stary Network
w3f/Open-Grants-Program pull request #233
Opened 2021-01-31 05:10 UTC by poria-cat

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-01-31 05:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=233) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=233) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=233) it.</sub>

2021-02-02 10:12 UTC, Noc2 requested changes
Thanks for the application. But why wouldn’t you use ERC721 for these use-cases? Are there similar initiatives in the ethereum ecosystem that show that there is actually the need for a third nft standard.

2021-02-02 11:59 UTC, poria-cat commented
Hi @Noc2 , thanks for the feedback. SubNFT is also using ERC721, it just needs some additional indexes to associate subNFT with NFT, so this is more like a special application of ERC721.
In the Ethernet ecosystem,[NIFTEX](https://landing.niftex.com/) can create and trade ERC20 fractions of NFTs. If needed, Starry can use the ERC721 to ERC1155 conversion to split the NFT and the bonding curve is added more easily

2021-02-05 09:10 UTC, Noc2 requested changes
Thanks for the update. Now, I have understood the concept and the reason behind it. Could you potentially integrate some contribution to the [PSP process](https://github.com/w3f/PSPs) process as part of the grant. Is there potentially already an Ethereum Improvement Proposals that addresses this issue?

2021-02-05 09:14 UTC, Noc2 commented
Btw. there is a new [Element](https://app.element.io/#/room/#web3nft:web3.foundation)/[Telegram](http://t.me/rmrkapp) chat group for all things NFT on Kusama and Polkadot.

2021-02-05 09:51 UTC, rrtti commented
@poria-cat Hi! A group of devs, PMs and designers, along with artists and NFT creators are working on a NFT strategy for Kusama network (already ongoing: https://kusama.polkassembly.io/post/303). The effort includes the development of Asset creator platforms (RMRK.app and PolkadotAssetJS - funded by treasury) and the development and maintenance of two pallets to be natively deployed on Kusama: ORML NFT pallet and a PoC NFT Gallery to work as a first experimentation in the direction of a native application.   We would love to discuss your project to see how it could align with our efforts on this: let me know what you think!

2021-02-05 10:15 UTC, usetech-llc commented
Most of these things are implemented already, we have 3 (or more) NFT pallets, refungibility (ERC1155) is also implemented and live on Unique. Ecosystem would benefit more from more downstream efforts to actually get that infrastructure to end users. More NFT wallets, minting solutions, advanced formats (like interactive NFTs), NFT relationships, advanced ownership structures, alternative economic models, etc., as well as real dapps - games, for example.

2021-02-05 11:12 UTC, poria-cat commented
> Thanks for the update. Now, I have understood the concept and the reason behind it. Could you potentially integrate some contribution to the [PSP process](https://github.com/w3f/PSPs) process as part of the grant. Is there potentially already an Ethereum Improvement Proposals that addresses this issue?

Glad to be able to contribute to the PSP process. There is no relevant proposal on the Ethernet, the protocol content will be updated later

2021-02-05 11:15 UTC, poria-cat commented
> @poria-cat Hi! A group of devs, PMs and designers, along with artists and NFT creators are working on a NFT strategy for Kusama network (already ongoing: https://kusama.polkassembly.io/post/303). The effort includes the development of Asset creator platforms (RMRK.app and PolkadotAssetJS - funded by treasury) and the development and maintenance of two pallets to be natively deployed on Kusama: ORML NFT pallet and a PoC NFT Gallery to work as a first experimentation in the direction of a native application.   We would love to discuss your project to see how it could align with our efforts on this: let me know what you think!

Hi, it's great to discuss the project together and contribute to the Polkadot's NFT ecosystem.

2021-02-05 11:19 UTC, poria-cat commented
> Most of these things are implemented already, we have 3 (or more) NFT pallets, refungibility (ERC1155) is also implemented and live on Unique. Ecosystem would benefit more from more downstream efforts to actually get that infrastructure to end users. More NFT wallets, minting solutions, advanced formats (like interactive NFTs), NFT relationships, advanced ownership structures, alternative economic models, etc., as well as real dapps - games, for example.

Hi, thanks for the suggestion, Unique is an amazing project, Starry's focus is on providing better mobility for NFT, I will make an update on the protocol later

2021-02-05 11:55 UTC, Noc2 commented
> Most of these things are implemented already, we have 3 (or more) NFT pallets, refungibility (ERC1155) is also implemented and live on Unique. Ecosystem would benefit more from more downstream efforts to actually get that infrastructure to end users. More NFT wallets, minting solutions, advanced formats (like interactive NFTs), NFT relationships, advanced ownership structures, alternative economic models, etc., as well as real dapps - games, for example.

Where can I find the open source code (for example ERC1155)?

2021-02-09 08:46 UTC, Noc2 requested changes
Thanks for the update, just to follow up on the above: Is there potentially already an Ethereum Improvement Proposals that addresses this issue? What do you mean with managing the NFTs in a DAO way? Do you already have a concrete idea how you are going to implement this? Also would it be possible to reduce the price a little bit further?

2021-02-09 09:46 UTC, poria-cat commented
> Thanks for the update, just to follow up on the above: Is there potentially already an Ethereum Improvement Proposals that addresses this issue? What do you mean with managing the NFTs in a DAO way? Do you already have a concrete idea how you are going to implement this? Also would it be possible to reduce the price a little bit further?

Maybe it's [eip-998](https://github.com/ethereum/eips/issues/998)

> What do you mean with managing the NFTs in a DAO way? Do you already have a concrete idea how you are going to implement this

Added an architecture image about nft dao for understanding

> Also would it be possible to reduce the price a little bit further?

Sure, Reduced from 14,000 dai to 12,000 dai

2021-02-10 08:39 UTC, Noc2 submitted a review, later dismissed
Thanks for the update. I also started to look a little bit into it. As pointed out [here](https://github.com/ethereum/EIPs/issues/864) it might not make sense to actually come up with an additional token standard for it. But there is also the [Re-Fungible Token](https://github.com/ethereum/EIPs/issues/1634) under development. So overall, I’m happy to go ahead with it and feel free to ping me once you start the discussion about a PSP. I will share the application with the rest of the team.

2021-02-10 10:55 UTC, poria-cat commented
> As pointed out [here](https://github.com/ethereum/EIPs/issues/864) it might not make sense to actually come up with an additional token standard for it. But there is also the [Re-Fungible Token](https://github.com/ethereum/EIPs/issues/1634) under development. 

Wow, these great references will give me more inspiration in future development.

> So overall, I’m happy to go ahead with it and feel free to ping me once you start the discussion about a PSP. I will share the application with the rest of the team.

Okay, I will. Thank you for all your work on this. @Noc2

2021-02-11 08:47 UTC, mmagician commented
@poria-cat That's indeed a novel proposal & I would like to support it, but in my opinion 12,000 DAI is overly excessive for the amount of work that the project entails.

Furthermore, thanks for adding the diagram for illustrating the operations of the NFTDAO submodule, but perhaps you could describe the details a bit more, or provide a couple of user stories to illustrate how the functionality of token management works from the different users' perspectives?

Lastly, some of your [demo links](https://friendly-mclean-d455eb.netlify.app/splitNFT) are unaccessible.

2021-02-11 10:29 UTC, poria-cat commented
Hi @mmagician , thanks for your review.

> but in my opinion 12,000 DAI is overly excessive for the amount of work that the project entails

Reduced from 12,000 dai to 10,000 dai. This is not an easy task because of the addition of NFT DAO.

> or provide a couple of user stories to illustrate how the functionality of token management works from the different users' perspectives?

Sure,  this was added to Additional Information

> Lastly, some of your demo links are unaccessible.

whoops, I forgot this was a page created using CRA and have solved the problem using hash router

2021-02-11 11:31 UTC, mmagician approved these changes
Alright, that makes a bit more sense now with the DAO, though I'm not sure about the extent to which people will use it - let's try and see. Thanks for the update, I'll be happy to support the project!

2021-02-11 11:35 UTC, Noc2 approved these changes

2021-02-11 13:25 UTC, poria-cat commented
Thanks for your support and let's look forward to the future together! @mmagician

2021-02-11 14:18 UTC, BenWhiteJam approved these changes

2021-02-11 14:23 UTC, merged

2021-06-21 16:38 UTC, mmagician commented
@poria-cat The ethereum payment address provided in your invoice and the address in your application don't match.
Please either:
1. Submit a new invoice with the same address as in the application.
2. Submit a PR to the original application to change your payout address.

2021-06-28 09:32 UTC, RouvenP commented
hi @poria-cat we transferred the payment for milestone 1.

2021-06-28 10:18 UTC, poria-cat commented
> hi @poria-cat we transferred the payment for milestone 1.

Sounds great, but I didn't get some Dai. 😭

2021-06-28 13:35 UTC, RouvenP commented
@poria-cat you're right, apologies - we sent it now :)

2021-06-28 13:52 UTC, poria-cat commented
Thanks @RouvenP, now I get it, lol. Thanks @Noc2 and @mmagician for all your help during this time!
Thanks to Web3 Foundation for giving me time to realize my idea, I hope Starry's batch minting, fragmented NFT and moloch-based DAO that can use NFT as a tribute will help more people!