Project_Splyt grant proposal.
w3f/Open-Grants-Program pull request #258
Opened 2021-02-15 01:40 UTC by dipenjoshi

# Grant Application Checklist

- [x ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [ x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x ] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-02-15 01:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=258) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: cyruskind<br/>:x: dipenjoshi<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=258) it.</sub>

2021-02-15 09:47 UTC, Noc2 requested changes
Thanks for the application. The formatting currently seems to be a little bit off. Also could you integrate the total costs of your application and change the BTC price to USD, see https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#overview-1 We recently updated the template. Furthermore the grants program only focuses on the development of open source software. For example we don’t fund things like "Soft Launch Mainnet" and we would need more technical details regarding your deliveries (e.g. programming language). Also we don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point.

2021-03-04 08:16 UTC, Noc2 commented
I’m closing this PR due to inactivity. Let me know if you want to reopen it.

2021-03-04 08:16 UTC, closed without merging

2021-03-05 00:13 UTC, cyruskind commented
Thanks @Noc2 We will open another shortly that is more focused on Substrate NFTs, atomic swap NFTs, etc.