Create vera_defi.md
w3f/Open-Grants-Program pull request #281
Opened 2021-02-25 03:24 UTC by arbach

Initial grant application

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-02-25 03:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=281) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=281) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=281) it.</sub>

2021-02-25 08:26 UTC, Noc2 requested changes
Thanks for the application. The links to your POC aren’t working for me: https://github.com/veraprotocol/defi or http://18.219.122.155/?rpc=ws%3A%2F%2F18.219.122.155%3A9944#/explorer Also, where can I find more information about the AssetManager module and it’s functionality?

2021-02-26 01:40 UTC, arbach commented
Repo was turned private by mistake. I also brought the nodes and app up. Sorry about that. 

AssetManager is Ink smart contract, there is description about it on the READ.ME in the repo. 

We are working on adding more documentation.

Thank you.

2021-02-26 09:03 UTC, Noc2 requested changes
Thanks for sharing. It’s nice to see that you already started to work on the AssetManager. Which additional features do you plan to integrate as part of the grant? Could you add more technical details to the application itself (e.g. lending manager etc.). What programming languages are you planning to use for the UI and what functionality will you implement in the UI? Do you already have an initial draft of the design?

2021-03-01 01:20 UTC, arbach commented
We are working on more technical specification for the milestone, including the UI and contracts. Will update application soon.  
UI will be in react as you can see in the tech stack already included in the application. 
In the application we included clickable wireframe. The actual design will be part of the grant, as we want to make sure it's top quality work. Design and UX are essential for the long term success of this project. 
Thanks for the feedback!

2021-03-01 09:01 UTC, Noc2 commented
Thanks. Feel free to ping me once you’ve updated the application.

2021-03-08 16:18 UTC, arbach commented
David, please check we have added more details to our application. Application now includes

2021-03-15 01:49 UTC, arbach reviewed
David, if you please review at your convince.

2021-03-15 15:05 UTC, Noc2 commented
@denislam also needs to sign the CLA.

2021-03-15 15:13 UTC, Noc2 requested changes
Thanks for the updated application. Could you also update the table with the Deliverables and Specification? For example you defined NFT Lending and I’m not sure it’s actually part of the deliverables. Also what do you mean with “Continue the development of our NFT.”?

2021-03-17 20:02 UTC, arbach commented
David, Thank you for the review. 

Yes, NFT lending is part of this, sorry about the confusion. I have updated the table. There are details on the NFT itself in under the milestone details. 

Would love to hear any feedback you have, negative before positive.

Thanks

2021-03-22 14:55 UTC, Noc2 requested changes
Thanks for the update and sorry for the late reply. I have two more questions: Could you also integrate more information regarding the User Interface? For example programming languages, support for the polkadot.js extension, etc. and I noticed that the attribution in your code seems to be missing: https://github.com/veraprotocol/defi  and https://github.com/paritytech/ink/tree/master/examples Could you clarify this?

2021-03-23 04:12 UTC, arbach commented
David, 

We have discussed and added the license to our code. 

As for the UI, it will built with React mostly coded with TypeScript, and we will rely on Polkadot.js to sign transaction, that is already included in our wireframe.

2021-03-23 07:40 UTC, Noc2 requested changes
Thanks for the quick response. But the repo still doesn’t contain any license file, nor any reference to the code, which originally was developed by parity. At least as far as I can see it.

2021-03-25 00:21 UTC, arbach commented
Sorry about that. We have added missing attribution to all relative files. 

We are eager to work with you, let me please if there is anything else we can do to make sure our project is accepted in the program. 

If you think we need to add more technical details, or elaborate on the business further we are more than happy to do it. 

Thanks.

2021-03-25 08:02 UTC, Noc2 commented
Thanks for adding the additional attribution and details. To be honest, I’m personally at the moment not convinced by your application but I will share it already with the rest of the team. Also are you aware of the [Element](https://app.element.io/#/room/#web3nft:web3.foundation)/[Telegram](http://t.me/rmrkapp) chat group for all things NFT on Kusama and Polkadot. Also something you should be aware is that: A group of devs, PMs and designers, along with artists and NFT creators are working on a NFT strategy for Kusama network (already ongoing: https://kusama.polkassembly.io/post/303).

2021-03-25 13:49 UTC, mmagician commented
> research and implement attributes and functionalities to link Token to real assets, such as hash or signature of scan of Art, and other proprietary techniques.

This is just adding a metadata to the token, nothing new here.

---
> Add support for perpetual royalties to original creator

This is covered by [ERC-2665](https://github.com/ethereum/EIPs/issues/2665), so I'm not sure what further research you need to do in this front (and adapting ink!'s erc721 to support this feature should be trivial).

---
We also don't provide support for the UX design phase as part of grants, as we believe this should form part of the team's investment and market research, and normally should be provided as part of the application. In your case, it's a benefit that you already provided wireframes, thanks for that.

---
With the above two points in mind, your list of core deliverables is halved. I think the idea you have might have some potential and I would be happy to support your project for a smaller amount. Let me know if this makes sense!

2021-03-25 16:59 UTC, semuelle commented
On top of what @mmagician mentioned, given that the aspect of linking real-world assets to NFTs isn't part of this application, it isn't a good selling point in the context of a grant. I would be keen to support a more generalised smart contract lending library, though.

2021-03-26 20:36 UTC, arbach commented
> Thanks for adding the additional attribution and details. To be honest, I’m personally at the moment not convinced by your application but I will share it already with the rest of the team. Also are you aware of the [Element](https://app.element.io/#/room/#web3nft:web3.foundation)/[Telegram](http://t.me/rmrkapp) chat group for all things NFT on Kusama and Polkadot. Also something you should be aware is that: A group of devs, PMs and designers, along with artists and NFT creators are working on a NFT strategy for Kusama network (already ongoing: https://kusama.polkassembly.io/post/303).

David, thanks for the great valuable feedback, this is exactly what we are looking for. We already  joined both these group and will start discussion the best fit for our solution in the ecosystem based on their feedback and need. Our primary goal is to bring our industry connections, and technical knowledge to the Polkadot ecosystem to  learn, contribute, and be part of the success of the wider ecosystem. We will keep you posted as our business evolve as we engage further with the community.

2021-03-26 21:47 UTC, arbach commented
> > research and implement attributes and functionalities to link Token to real assets, such as hash or signature of scan of Art, and other proprietary techniques.
> 
> This is just adding a metadata to the token, nothing new here.
> 
> > Add support for perpetual royalties to original creator
> 
> This is covered by [ERC-2665](https://github.com/ethereum/EIPs/issues/2665), so I'm not sure what further research you need to do in this front (and adapting ink!'s erc721 to support this feature should be trivial).
> 
> We also don't provide support for the UX design phase as part of grants, as we believe this should form part of the team's investment and market research, and normally should be provided as part of the application. In your case, it's a benefit that you already provided wireframes, thanks for that.
> 
> With the above two points in mind, your list of core deliverables is halved. I think the idea you have might have some potential and I would be happy to support your project for a smaller amount. Let me know if this makes sense!

Marcin, we appreciate the valuable feedback. 

For the attributes, our long term intention is to bring more industry standard to the on chain data to incorporate things like ISO 25178 to have better traceability of physical assets and their digital representation.  

Yes, indeed [ERC-2665](https://github.com/ethereum/EIPs/issues/2665) already provide strong foundation, however we are hoping to provide more comprehensive royalty structures. Complete understand if you think this doesn't add value to the ecosystem. 

Thanks for the clarification on the UI/UX. Our team is heavily invested in this, and will cover that aspect of the expense. 

Having said that, our primary objective is the engagement with the community to make sure what we are building has value for everyone. We highly appreciated your generous support and happy to take a smaller amount you suggest for this project.

2021-03-26 21:53 UTC, arbach commented
> On top of what @mmagician mentioned, given that the aspect of linking real-world assets to NFTs isn't part of this application, it isn't a good selling point in the context of a grant. I would be keen to support a more generalised smart contract lending library, though.

Sebastian, thank you for the valuable feedback!  we talk about physical assets to give context for our overall vision as recommended by the grant guideline, sorry if we took this too far in this application. At it's heart this is a lending smart contract. and will be available for use by other under open source license. We are open to put more effort to make our smarts in a well documented library to be used by other as well. 

Let me please know if you have further suggestion to help us gain your support for our project. 

Thank you.

2021-03-29 07:49 UTC, mmagician commented
@arbach We are generally happy to support a research phase, although in general I would see it as a separate grant. In this case, however, I'm not sure what the outcomes/deliverables of such a research phase would contribute, so without seeing a concrete proposal it's hard to judge.
Nevertheless, my personal suggestion would be to decouple NFT specifications from the rest. For this grant I suggest to focus on the AssetManager & the ExchangeManager, given that we've already got plenty of similar NFT grants. @semuelle @Noc2 do you think that would make sense?

2021-03-29 20:29 UTC, semuelle commented
> the AssetManager & the ExchangeManager

@mmagician Isn't the ExchangeManager rather common? Agreed on the AssetManager, though.

2021-03-30 16:48 UTC, arbach commented
Let us please know if there are any other clarification from our side you need. or anything else we can do to make sure we start this partnership. Thanks

2021-03-30 19:41 UTC, mmagician commented
@arbach 
> For this grant I suggest to focus on the AssetManager

If you're ok with it, you can go ahead and change the scope of the application to reflect that. You should be able to integrate with existing NFT implementations, rather than building another one anew.

2021-03-30 21:38 UTC, arbach commented
> If you're ok with it, you can go ahead and change the scope of the application to reflect that. You should be able to integrate with existing NFT implementations, rather than building another one anew.

@mmagician 

I have update our application accordingly.

2021-03-31 07:03 UTC, mmagician commented
Thanks for your flexibility.
As I [pointed out before](https://github.com/w3f/Open-Grants-Program/pull/281#issuecomment-806781546):
> With the above two points in mind, your list of core deliverables is halved. 

I believe you still should adjust the price accordingly.

2021-03-31 12:54 UTC, arbach commented
@mmagician   Sorry I missed that. fixed.

2021-03-31 15:59 UTC, alxs approved these changes
Happy to go ahead with this.

2021-04-01 06:54 UTC, mmagician approved these changes
Alright, let's give it a try

2021-04-01 07:17 UTC, Noc2 approved these changes

2021-04-01 07:18 UTC, merged

2021-04-01 16:47 UTC, arbach commented
@mmagician  @Noc2  @alxs @semuelle , web3 team

We , the Vera team, are grateful for the trust you put in us, and we are thrilled for your approval for our project, and looking forward to complete this work and move forward with you!

2021-06-23 04:44 UTC, arbach commented
Hello web3 team, 

Wanted to keep you posted that our work on this was done a while back, we did not have time wrap up the delivery for it yet. 

here is the beta app.  http://beta.vera.financial/
and recorded demo https://drive.google.com/file/d/16sUVt-wvYdWAUsfupGVtnzWDOvYAbio6/view
and here is the source code https://github.com/veraprotocol/ambrosia

Working on putting together all documents required for the delivery, and submitting as per instruction. 

Sorry we are late on this, we had multiple good partnerships that we had to do tech work for that delay this specific project. 

Looking forward to continuing the collaboration.

2021-06-23 08:13 UTC, semuelle commented
Thanks for the update, @arbach. Looking forward to your delivery.