Open Grants Program application for project Delmonicos
w3f/Open-Grants-Program pull request #283
Opened 2021-02-26 06:39 UTC by lumena-tech

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-02-26 06:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=283) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: lumena-tech<br/>:x: adetante<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=283) it.</sub>

2021-02-26 09:26 UTC, Noc2 requested changes
Thanks for the application. This sounds like an interesting project. I have a few questions: 

- Could you also fill out the overview section (Total Costs, etc.)? 
- Additionally could you clarify which data you plan to store on-chain (for example as part of the Charger module)? 
- Do you already know which modules you are planning to use, for example regarding Identity. If so could you directly link to them as part of the deliverables (see [identity module](https://github.com/paritytech/substrate/tree/master/frame/identity)). 
- How do you plan to deal with potential privacy issues in case all the data is stored on-chain or are you planning to use an additional off-chain storage solution? 
- Do you already have simple mock-ups or drafts for the front-end?

2021-02-26 21:18 UTC, lumena-tech commented
Regarding the questions asked by Noc2 : 
* Could you also fill out the overview section (Total Costs, etc.)?
  * Sorry we missed that. That's done.
* Additionally could you clarify which data you plan to store on-chain (for example as part of the Charger module)?
  * We have added a paragraph named "Data Management" in section Project Details to give more detail on that subject 
* Do you already know which modules you are planning to use, for example regarding Identity. If so could you directly link to them as part of the deliverables (see identity module).
  * We have added hyperlinks to modules identity, membership and contracts in milestones description. 
* How do you plan to deal with potential privacy issues in case all the data is stored on-chain or are you planning to use an additional off-chain storage solution?
  * We have added a paragraph named "Data Management" in section Project Details to give more detail on that subject 
* Do you already have simple mock-ups or drafts for the front-end?
  * No we don't have any mockups nor drafts for the front-end. We can try to work on it if it is required.

2021-02-27 14:36 UTC, Noc2 approved these changes
Thanks for the quick reply and the updates to the application.Usually we ask teams to provide some initial designs for the UI in case the front end is the clear focus of the application. But I’m happy to go ahead with the project without this, since I guess the design isn’t so important for this kind of PoC. I will share the application with the rest of the team.

2021-03-01 16:25 UTC, lumena-tech commented
> Thanks for the quick reply and the updates to the application.Usually we ask teams to provide some initial designs for the UI in case the front end is the clear focus of the application. But I’m happy to go ahead with the project without this, since I guess the design isn’t so important for this kind of PoC. I will share the application with the rest of the team.

Thanks a lot. Don't hesitate if you need more details.

2021-03-02 11:52 UTC, gautamdhameja commented
LGTM! Would it be possible to show a demo of the working solution as part of the Milestone 3 delivery? A recorded video or the solution deployed in some VM?

2021-03-02 11:55 UTC, gautamdhameja submitted a review, later dismissed
LGTM! Would it be possible to show a demo of the working solution as part of the Milestone 3 delivery? A recorded video or the solution deployed in some VM?

2021-03-02 12:43 UTC, lumena-tech commented
Yes of course. Should I modify the Application to include that in the deliverables  ?

--
Fabrice CROISEAUX

Le 2 mars 2021 à 12:55:58, Gautam Dhameja (notifications@github.com<mailto:notifications@github.com>) a écrit:

@gautamdhameja approved this pull request.

LGTM! Would it be possible to show a demo of the working solution as part of the Milestone 3 delivery? A recorded video or the solution deployed in some VM?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/w3f/Open-Grants-Program/pull/283#pullrequestreview-601734534>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASYNAZ6SYQE6VURQRG4E7MDTBTG45ANCNFSM4YH4KWCA>.

2021-03-02 18:35 UTC, Noc2 commented
> Yes of course. Should I modify the Application to include that in the deliverables ?

That would be great! Thanks.

2021-03-03 08:36 UTC, lumena-tech commented
> > Yes of course. Should I modify the Application to include that in the deliverables ?
> 
> That would be great! Thanks.

That's done !

2021-03-04 08:57 UTC, Noc2 approved these changes

2021-03-04 09:25 UTC, lumena-tech commented
Can you please tell us what are the next steps before knowing if our project is accepted or not ?
Thanks a lot and  best regards.

2021-03-04 09:35 UTC, Noc2 commented
> Can you please tell us what are the next steps before knowing if our project is accepted or not ?
> Thanks a lot and best regards.

Three people need to approve the PR in order to accept the grant. Once the grant is accepted you can start working on it and submit the milestone [here](https://github.com/w3f/Grant-Milestone-Delivery) once you finished with it. You can find the full process [here](https://github.com/w3f/Open-Grants-Program#pencil-proces

2021-03-04 10:20 UTC, gautamdhameja approved these changes

2021-03-06 08:58 UTC, lumena-tech commented
We have created an organisation dedicated to Delmonicos and moved our repos. I probably shouldn't have update the application because the existing reviews have been dismissed. Sorry !

2021-03-08 07:42 UTC, Noc2 approved these changes

2021-03-09 16:33 UTC, gautamdhameja approved these changes

2021-03-10 06:15 UTC, lumena-tech commented
As you can see we have started to work on the project. Don't hesitate if you need more details to have the third approval. For information, this project will be described as a use case during a workshop organised by European Cenral Bank focussed on use cases for CBDC relating to machine to machine (M2M) payments

2021-03-10 15:09 UTC, alxs approved these changes

2021-03-10 15:09 UTC, merged

2021-12-03 08:36 UTC, lumena-tech commented
Hi Alexio,

Yes we are still planning to release the last version. The only remaining part is the validation of the Medium article. We should come back to you soon.
Sorry for the delay.



-------------------------

Fabrice Croiseaux

Président

Lumena

2 rue Maurice Barrès

57000 METZ FRANCE

Mobile : +33 6 42 06 23 43

***@***.******@***.***>

https://www.linkedin.com/in/fcroiseaux/

http://www.lumena.tech


Les informations contenues dans cet email peuvent être confidentielles ou protégées par des lois en vigueur. Elles sont à l'attention des destinataires uniquement. Les données nominatives éventuelles ne peuvent être communiquées à des tiers par le récepteur de cet email.

Si vous n'êtes pas le destinataire principal, ni un des destinataires placés en copie, la divulgation, la copie, la diffusion ou toute autre utilisation de cet email est prohibée et peut être illégale. Dans ce cas, merci d'avertir l'émetteur immédiatement et de détruire cet email.

P Please consider the environment before Printing this email


Le 1 décembre 2021 à 15:50:35, Aleixo Sanchez ***@***.******@***.***>) a écrit:

@lumena-tech<https://github.com/lumena-tech> it's been a while since your last delivery now, care to share a quick status update? Are you still interested in submitting the last milestone?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/w3f/Grants-Program/pull/283#issuecomment-983715900>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASYNAZY2XKQ2SIYTLFXRY7TUOYY3PANCNFSM4YH4KWCA>.

2022-01-06 11:06 UTC, alxs commented
@lumena-tech friendly reminder.

2022-01-06 14:41 UTC, lumena-tech commented
Hi,

Thanks for the reminder. The team is currently in Vegas for the CEX (the project based on Polkadot has been selected by the French Tech to be one of the French startup representing France at CES) and we plan to submit the third iteration second half of January.

Sorry for the delay,

Best regards,

Fabrice.


-------------------------

Fabrice Croiseaux

Président

Lumena

2 rue Maurice Barrès

57000 METZ FRANCE

Mobile : +33 6 42 06 23 43

***@***.******@***.***>

https://www.linkedin.com/in/fcroiseaux/

http://www.lumena.tech


Les informations contenues dans cet email peuvent être confidentielles ou protégées par des lois en vigueur. Elles sont à l'attention des destinataires uniquement. Les données nominatives éventuelles ne peuvent être communiquées à des tiers par le récepteur de cet email.

Si vous n'êtes pas le destinataire principal, ni un des destinataires placés en copie, la divulgation, la copie, la diffusion ou toute autre utilisation de cet email est prohibée et peut être illégale. Dans ce cas, merci d'avertir l'émetteur immédiatement et de détruire cet email.

P Please consider the environment before Printing this email


Le 6 janvier 2022 à 12:06:17, Aleixo Sanchez ***@***.******@***.***>) a écrit:

@lumena-tech<https://github.com/lumena-tech> friendly reminder.

—
Reply to this email directly, view it on GitHub<https://github.com/w3f/Grants-Program/pull/283#issuecomment-1006483066>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASYNAZYFKHA5XVB4Y2SG3ALUUVZSNANCNFSM4YH4KWCA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-06 15:07 UTC, alxs commented
No worries. Thanks for the update, and congratulations!

2022-02-14 13:09 UTC, alxs commented
@lumena-tech another reminder. If you can't submit within the next two weeks, please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the original timeline.