Semantic EventFlow Contracts
w3f/Open-Grants-Program pull request #287
Opened 2021-03-01 15:53 UTC by AleDvin

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-03-01 15:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=287) it.</sub>

2021-03-02 08:56 UTC, alxs commented
Hi @AleDvin and thank you for your application. Looks interesting! Just one quick detail, we've recently updated the application template to reflect the fact that grants now need to be denominated in USD (payment may still be in BTC or DAI). Could you update this?

2021-03-02 09:12 UTC, AleDvin commented
Hi @alxs. I have updated the application.

2021-03-04 10:07 UTC, Noc2 requested changes
Thanks for the application. I have a few questions: 

- Just for my understanding, you basically plan to implement a special event flow based smart contract language, which is not turing complete correct? The state machine still needs to verify these transactions on-chain and it’s unrelated to blockchain [events](https://wiki.polkadot.network/docs/en/build-protocol-info#events).  
- What’s the reason you want to use substrate instead of Apla for it? 
- What programming language/framework are you planning to use for the client? 
- Why do you think nobody successfully implement something like this before?

2021-03-04 11:41 UTC, alxs commented
Something from my side: we generally recommend teams to split the development into smaller milestones of around 1 month each and to split deliverables into smaller, more concise ones. E.g. deliverable one could be split into three separate ones containing validating transactions, model execution according to inputs, and writing the results; each named after the corresponding function and specifying some requirements for these functions. This also makes our task of evaluating the milestones easier. Also specifying broad terms such as "full-featured" is a good idea.

Besides, @Noc2 correct me if I wrong but I think we usually don't fund parachain-related costs, i.e. we could fund the development of the protocol but you'd have to cover the costs of parachain integration and deployment yourself (though I think given the scope of the grant, this is a given).

2021-03-04 12:10 UTC, AleDvin commented
Hi. @Noc2
The EventFlow models semantic language was originally created for describe business processes. It is't a programming language, but a modeling language. Several PoCs  of use EventFlow controller demonstrated that the language allows modeling complex time-distributed counterparty relationships. It is necessary to distinguish between a controller (written in a standard programming language - now C #)  that executes a action model and the semantic model itself, which describes the events of a business process.

The execution of semantic models is not related to events on the polkadot blockchain. EventFlow action model (for example, some agreement) is stored in the chain as a separate contract. A network transaction involving one or more events from the client is sent to this  contract-model. The EventFlow controller validates the transaction and execute the model with the received events. In this case, the controller with the model should be considered as a normal “smart contract” running in a virtual machine. That is, we have one immutable Turing-complete “contract” for all possible models. The result of the model execution is written into the memory of the model contract. (Although other implementations are possible, say, with a unified event store).

The Apla project is frozen now and the team has been disbanded. The Apla blockchain network has not passed load testing. The Apla backend is written as a monolith and is not modifiable. I am interested in developing my technology in a wider community that Apla does not have.

We are planning to use Rust and for client and for the EventFlow model controller (the controller will be rewritten).

I got acquainted with projects that tried to use semantic languages to describe the business processes of smart contracts. Most often, these were options for generating solidity code based on mnemonics. The projects were not successful because they used an object ontology, which is not suitable for describing actions (business processes). I am the author of an event ontology and I myself have developed a language for modeling executable models based on the dataflow architecture. The technology has recently successfully passed PoC while solving security event stream processing problems in one IT company. However, it is important for me to apply the EventFlow method in the design of public trusted networks.

2021-03-04 12:40 UTC, AleDvin commented
Hi @alxs. I am aware of your recommendation about smaller milestones. However, the EventFlow architecture consists of three parts: backend, client and ontology (contract  semantic language), which should not be designed sequentially, but in parallel. They must all work together. Therefore, we have a problem with a time stages separation.

We plan to initially implement the project on an independent Substrate chain. Moving it to parachain we will be discussed by the end. (Consultations for our programmer are still needed here). 

P.S. Sorry for my English. He's not very good.

2021-03-04 13:25 UTC, AleDvin commented
To @alxs. The client that is currently running does not have all the features (for example, it does not support roles). The word "full-featured" means support of all elements of the semantic language required to describe contracts.

2021-03-04 16:32 UTC, alxs commented
Thank you for your clarifications @AleDvin. Could you integrate these into your application and remove mentions of a parachain?

However from my side, I regret to inform you that after further review I will not be moving forward with your application due to the following reasons:
- Your team isn't particularly active on GitHub (2 out of the 3 team members have no activity in the past year). Besides, I assume no familiarity with rust for the whole team. Feel free to point out relevant experience or provide examples of projects recently carried out by team members elsewhere.
- Since this project specifically addresses business needs: I kinda see use cases for this, but nothing that couldn't be achieved with other solutions. Perhaps providing specific examples would help here.
- Even if your project consists of interoperable components, I would consider it good project management to split the work into smaller milestones that can be separately achieved, which also allows us to provide feedback early on in the development. Given my additional concerns, I think a single-milestone 3 month grant is a bad idea.
- Since as far as I can see you have no current affiliations and/or partnerships, I fear that you wouldn't be able to maintain the project after completion of the grant. Feel free to point this out if that is not the case.

Don't worry though! The committee currently consists of 10 members, and you only need to convince 3 of them in order for your application to be accepted. So you still stand good chances.

2021-03-05 09:30 UTC, AleDvin commented
Hi @alxs 
Thanks for your questions and advice.
- The team hoped for the continuation of the Apla project all year and did not participate in other projects.
- The Semantic EventFlow Contracts project has important advantages: (1) The user does not write a contract in one of the programming languages, but describes the business logic in the format of events, which is extremely important for the network safety. (2) Contracts can write, read and validate business analysts, not professional programmers.
- I see only one opportunity to split the project into two stages. (1) First create a custom client that implements models writing and execution locally (without a network). (2) At the second stage, embed the contract controller (EventFlow models) into the backend, that is, implement the smart contract network protocol. The amount of the grant can be discussed.
- The Semantic EventFlow Models controller is universal and can be used in any area, as a workflow engine. It should be considered as a standalone product that will be supported regardless of its use in different projects. In fact, we are talking about Polkadot's participation in the development of a new semantic technology.

2021-03-18 00:49 UTC, alxs commented
Closing due to inactivity. Feel free to reopen the application with a proposal that contains all clarifications from the discussion above.

2021-03-18 00:49 UTC, closed without merging