Create DSIP.md
w3f/Open-Grants-Program pull request #308
Opened 2021-03-09 13:33 UTC by NetGodFather

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-03-09 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=308) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=308) it.</sub>

2021-03-11 14:50 UTC, Noc2 requested changes
Thanks for the application and sorry for the late reply. I have a few questions/comments:

- Did you previously already work on similar projects? Would it be possible to share previous open source projects or something similar?
- Do you have a whitepaper or something similar? 
- How is your solution and the deliveries different from [Acala](https://github.com/AcalaNetwork/Acala). For example, could you not simply reuse their oracle, assets etc. implementation? 
- Also this “stablecoins can be tied not only to fiat coins, but also to the value of stocks, futures, precious metals, or even to a combination of assets.” sound like a synthetic asset protocol which is currently for example developed by [laminar](https://github.com/laminar-protocol/laminar-chain). How is your solution different/unique?

2021-03-12 04:27 UTC, NetGodFather commented
@Noc2 

Thanks for your comment.

> Did you previously already work on similar projects? Would it be possible to share previous open source projects or something similar?

(1) The team was mainly engaged in Internet before, and had never done similar projects;
(2) In the last 2-3 years, we have done some outsourcing smart contract projects;
(3) GitHub has the code (ChainCommerce) that participated in the hackathon of a federation chain (FISCO-BCOS) in the early days.

> Do you have a whitepaper or something similar?

The white paper is in preparation and is expected to be available in a first edition within a week.

> How is your solution and the deliveries different from [Acala](https://github.com/AcalaNetwork/Acala). For example, could you not simply reuse their oracle, assets etc. implementation?

(1) We have a plan to introduce ORML related modules for development, such as: orml-oracle, orml-currencies;
(2) Oracle is still evaluating whether to link to parallel chains via relays or to connect directly to trusted providers using OCW;
(3) In the first stage, the main development tasks will be focused on the logical implementation of the issue protocol, pledge issue and clearing auction.

> Also this “stablecoins can be tied not only to fiat coins, but also to the value of stocks, futures, precious metals, or even to a combination of assets.” sound like a synthetic asset protocol which is currently for example developed by [laminar](https://github.com/laminar-protocol/laminar-chain). How is your solution different/unique?

The DSIP differs from the Laminar in:
(1) Laminar is used to exchange stablecoins for other currencies by pledging USD stablecoins, while DSIP can issue stablecoins by pledging a variety of assets (such as BTC, ETH, DOT, etc.).
(2) Laminar provides a service to exchange stablecoins for other assets, while DSIP provides an infrastructure for stablecoin issuance.Based on DSIP, any organization can issue stablecoins by making its own pledge issuance rules, rather than having to passively accept the existing issuance rules.On the DSIP, multiple laminar -like services can be provided.

2021-03-17 14:07 UTC, NetGodFather commented
Based on internal team evaluation, we temporarily withdraw the application. We will then make some adjustments and reapply for Grants. 
thank you!

2021-03-17 14:07 UTC, closed without merging