Create RubyProtocol.md
w3f/Open-Grants-Program pull request #311
Opened 2021-03-13 09:31 UTC by rubyprotocol

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-03-13 09:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=311) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=311) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=311) it.</sub>

2021-03-17 20:39 UTC, alxs commented
Excellent application and exciting project, I'm 100% willing to support this. I just have a few minor comments:
- http://rubyprotocol.com/ is currently empty. I suppose it's still under construction, but just checking that it wasn't a misspelling.
- I suppose you switched from smart contracts to a pallet at some point while you were writing your application, which is indeed much better suited to your requirements. However smart contracts are still mentioned several times in the text and listed as an objective under `Open API and SDK`. This section and the delivery items under `Project Architecture` are also almost identical and the UI is not listed in the latter.
- Deliverables 0a-d in the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) need to be included in each milestone.

2021-03-24 08:32 UTC, rubyprotocol commented
> Excellent application and exciting project, I'm 100% willing to support this. 

_Thanks for your support._ 

I just have a few minor comments:
> 
> * http://rubyprotocol.com/ is currently empty. I suppose it's still under construction, but just checking that it wasn't a misspelling.

_Yes, it is still under construction._ 

> * I suppose you switched from smart contracts to a pallet at some point while you were writing your application, which is indeed much better suited to your requirements. However smart contracts are still mentioned several times in the text and listed as an objective under `Open API and SDK`. This section and the delivery items under `Project Architecture` are also almost identical and the UI is not listed in the latter.

_We have already replaced "smart contract" with "substrate module" in the proposal. UI has been included in both the `Open API and SDK` section and the deliverables section of `Project Architecture`._ 

> * Deliverables 0a-d in the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) need to be included in each milestone.

_We have already included the deliverables 0a-d in the updated proposal._

2021-03-24 11:26 UTC, alxs commented
Thank you for the changes. I have a few follow-up questions:
- Do you have any candidates for the untrusted cloud, and who will carry the hosting expenses? Would this be something like AWS and would you consider using a decentralised solution like IPFS? This is currently [partially implemented](https://github.com/rs-ipfs/rust-ipfs) in Rust.
- Can data owners withdraw their consent to their data being processed? If they lost their private keys, not only would they not be able to do so but they would be locked out of any future returns.
- Whose is the certified signature `Sig_D(FE.Enc(x))`? If this is not the owner's, owner and provider will need to coordinate in order to upload the encrypted data, and if it is the owner it is superfluous. What would the provider's incentive be to play their part?
- In the current design, data owners could cheat purchasers by (passively) accepting payment for some computation but then immediately removing their data from the cloud. This could be prevented by requiring the data purchaser to retrieve the data beforehand.
- How will you ensure that data owners/providers have legal rights to monetise this data?
- What approach will you take to guarantee that the data is well-formed and _real_?

2021-03-26 02:41 UTC, rubyprotocol commented
> Thank you for the changes. I have a few follow-up questions:
> 
> * Do you have any candidates for the untrusted cloud, and who will carry the hosting expenses? Would this be something like AWS and would you consider using a decentralised solution like IPFS? This is currently [partially implemented](https://github.com/rs-ipfs/rust-ipfs) in Rust.

_The decentralized cloud such IPFS is definitely on our radar. As for the hosting expenses, the project might pay for it initially to jump-start the project, but we will gradually transfer the cost to the data owner since it would make sense for them to pay for their data monetization business._ 

> * Can data owners withdraw their consent to their data being processed? If they lost their private keys, not only would they not be able to do so but they would be locked out of any future returns.

_The only FE algorithm the data owner needs to run is the encryption algorithm. There exist many revocable FE schemes in the literature to ensure the data owner can withdraw their consent without involving any of their private information, such as the revocable FE scheme proposed in this work: https://link.springer.com/chapter/10.1007/978-3-319-49890-4_14. The data owner might have a secret key for their own wallet to collect their monetization return, but this key is entirely independent of the FE scheme._ 

> * Whose is the certified signature `Sig_D(FE.Enc(x))`? If this is not the owner's, owner and provider will need to coordinate in order to upload the encrypted data, and if it is the owner it is superfluous. What would the provider's incentive be to play their part?

_In our current proposal, D is the data source, which the entity that generates the data for the data owner. For instance, in the genomic case, D could be the genomic testing company generating the DNA data for the data owner. It would be pretty easy for the data owner, as a client of the company, to obtain a signature on the encryption of the DNA data._ 

> * In the current design, data owners could cheat purchasers by (passively) accepting payment for some computation but then immediately removing their data from the cloud. This could be prevented by requiring the data purchaser to retrieve the data beforehand.

_Thanks for pointing that out. Will add this to the updated version._ 

> * How will you ensure that data owners/providers have legal rights to monetise this data?

_The whole monetization process will be compatible with the relevant law such as GDPR. We will consult with our legal team before we officially launch our product._ 

> * What approach will you take to guarantee that the data is well-formed and _real_?

_The well-formedness of the data owner's data is guaranteed in two ways in our proposal: 1. as mentioned above, a signature from the data source will guarantee it's obtained from the right source. 2. when the data purchaser receives the functional key from the key distributor, it will be attached with a zero-knowledge proof demonstrating that it corresponds to the function the data purchaser is interested in._

2021-03-30 16:37 UTC, alxs commented
Thank you for your answers. Could you keep integrating these into the application?

I think the distinction between data owner and data source is currently not very clear in your proposal and I'm still confused as to their roles. E.g. in the application, for the genomic data example you state that
> The secret key might be generated by the hospital that collects the users' genomic data or the data owner themselves. 

If the data source is the one that generates the secret key, don't they effectively become the data owner?

As I see it in most cases the data sources will be the only ones with large enough and hopefully monetisable datasets anyway, but you expect each individual owner of a piece of that data to submit it individually, correct? Why not leave owner compensation in the hands of the data source and just interact with the latter? Otherwise, apart from the fact that it would be _much_ harder to achieve critical mass, I still think data sources are **not guaranteed to cooperate** and even if they do, they would probably demand compensation for their curation and verification efforts. I understand that removing data owners from the process may go against the philosophy of the project if what you intend is to put control of one's data back in the hands of the owner, but if this is indeed your intention, this distinction and the mentioned incentivisation challenge need to be addressed.

Otherwise, feel free to pivot to only deal with data sources (though I think data providers would be a more appropriate term) instead. My impression is that you've correctly identified it's not possible to do without a data provider in order to guarantee the correctness of the data, but also that said provider has a more important role than what may seem from your application and hence needs to either be further involved in the process or alternatively just take on the role of data owner.

In case I've misunderstood anything, just let me know. Otherwise I'd be happy to see significant changes to the proposal regardless of which one of the two approaches you choose to follow, but let me reiterate that I think this is a strong application and I'll be happy to share it with the rest of the team as soon as it's ready.

Lastly, please double check that ZeroPool is the appropriate tool for your project. [Manta Network](https://github.com/Manta-Network/pallet-manta-dap/) have implemented private payments with zkSNARKs using [ArkWorks](https://github.com/arkworks-rs/), which has seen significantly more development, and it seems to work well for them. Otherwise, could you just expand on why you prefer ZeroPool and what it provides that makes you consider it in the first place?

2021-04-03 05:43 UTC, rubyprotocol commented
> Thank you for your answers. Could you keep integrating these into the application?

_Sure, already integrate the update to the proposal._ 

> 
> I think the distinction between data owner and data source is currently not very clear in your proposal and I'm still confused as to their roles. E.g. in the application, for the genomic data example you state that
> 
> > The secret key might be generated by the hospital that collects the users' genomic data or the data owner themselves.
> 
> If the data source is the one that generates the secret key, don't they effectively become the data owner?
> 

_Even though the data source (the hospital) is the one that produces the data, it doesn't mean it owns the patients' data. For instance, according to this report (https://www.forbes.com/sites/forbestechcouncil/2018/04/23/who-really-owns-your-health-data/?sh=1499f91d6d62), some states explicitly give patients ownership of their health data. In other words, only the patient can dictate how the data should be monetized._ 

> As I see it in most cases the data sources will be the only ones with large enough and hopefully monetisable datasets anyway, but you expect each individual owner of a piece of that data to submit it individually, correct? Why not leave owner compensation in the hands of the data source and just interact with the latter? Otherwise, apart from the fact that it would be _much_ harder to achieve critical mass, I still think data sources are **not guaranteed to cooperate** and even if they do, they would probably demand compensation for their curation and verification efforts. I understand that removing data owners from the process may go against the philosophy of the project if what you intend is to put control of one's data back in the hands of the owner, but if this is indeed your intention, this distinction and the mentioned incentivisation challenge need to be addressed.
> 

_The whole point of this project is to let the real data owner take back control of their own data, and you are right that it would go against the ethos of this project if there is a third party (i.e., the data source) to represent the data owner to collect the monetization gain of their private data. Since the law dictates only the patients can decide how to monetize their private data, it would also be illegal to let the data source be their representatives and decide how to monetize the data. We envision the data source could charge a certain extra service fee from the data owner when the data owner first meets the data source (goes to the hospital and does the test) and decides to join the monetization program._ 

> Otherwise, feel free to pivot to only deal with data sources (though I think data providers would be a more appropriate term) instead. My impression is that you've correctly identified it's not possible to do without a data provider in order to guarantee the correctness of the data, but also that said provider has a more important role than what may seem from your application and hence needs to either be further involved in the process or alternatively just take on the role of data owner.
> 
> In case I've misunderstood anything, just let me know. Otherwise I'd be happy to see significant changes to the proposal regardless of which one of the two approaches you choose to follow, but let me reiterate that I think this is a strong application and I'll be happy to share it with the rest of the team as soon as it's ready.
> 

_Already add " The data source could charge an extra service fee from the data owner when the data owner first meets the data source (goes to the hospital and does the test) and decides to join the monetization program. " to the proposal._ 

> Lastly, please double check that ZeroPool is the appropriate tool for your project. [Manta Network](https://github.com/Manta-Network/pallet-manta-dap/) have implemented private payments with zkSNARKs using [ArkWorks](https://github.com/arkworks-rs/), which has seen significantly more development, and it seems to work well for them. Otherwise, could you just expand on why you prefer ZeroPool and what it provides that makes you consider it in the first place?

_What we need is an implementation of groth16 scheme. As specified in the readme of groth16 of ArkWorks, it is still a poc prototype, this is why we choose Zeropool._

2021-04-06 14:48 UTC, alxs commented
Thanks. Can I ask you to please add the answers in your last two comments *to the application* where appropriate?

I fully agree that it would be patently ill-advised to try to monetise health data derived from medical records, as well as illegal as pointed out in the report you link to. However, the rights to such data could have been waived or sold if they were collected in any other context, and this exemption only applies to the specific case of medical data.

But thanks for the clarification, knowing that you intend owners to always represent individuals does make the distinction clear between these and data sources. However could you in that case add the required interaction between owner and source to the UI deliverables of milestone 2? I.e. sources need to be able to register as such and to provide a signature, and owners need to be able to request a signature from a registered source which must then be verified on-chain.

I will share your application to the rest of the team for review pending the addition of your clarifications to the application.

2021-04-07 08:42 UTC, rubyprotocol commented
> Thanks. Can I ask you to please add the answers in your last two comments _to the application_ where appropriate?
> 

_Sure, since I have already made the necessary change regarding my comments to your question posted 8 days ago, I mostly make the change regarding my comments to your question posted 4 days ago this time. Please let me know if I have missed anything in my latest change._ 

> I fully agree that it would be patently ill-advised to try to monetise health data derived from medical records, as well as illegal as pointed out in the report you link to. However, the rights to such data could have been waived or sold if they were collected in any other context, and this exemption only applies to the specific case of medical data.
> 
> But thanks for the clarification, knowing that you intend owners to always represent individuals does make the distinction clear between these and data sources. However could you in that case add the required interaction between owner and source to the UI deliverables of milestone 2? I.e. sources need to be able to register as such and to provide a signature, and owners need to be able to request a signature from a registered source which must then be verified on-chain.
> 

Thanks for pointing this out, and I have already made the change to the specification of milestone 2 regarding the UI for the interaction between the data owner and source. 

> I will share your application to the rest of the team for review pending the addition of your clarifications to the application.

2021-04-12 10:18 UTC, alxs commented
Thanks. I'll forward the application to the others.

One last thing I forgot to mention was that, regardless of what both ZeroPool's and ArkWorks' READMEs say, I'm not sure ZeroPool can be considered much more than a PoC either. Perhaps it'd be a good idea to the code before choosing either of them.

2021-04-12 10:28 UTC, alxs approved these changes

2021-04-12 14:49 UTC, mmagician commented
Top proposal. So I imagine your first step of your M1.1 is to devise a Rust library for performing functional encryption like [GoFE](https://github.com/fentec-project/gofe) right? Are you going to base your work off an existing Rust project that does something similar? Also, do you plan to support all of modular arithmetic, pairings and lattices primitives or just focus on one of them?

2021-04-13 07:57 UTC, Noc2 requested changes
Thanks for your application. Looks interesting. What’s your relationship with the Kylin network? Do you have any previous code/experience which you could share? Could you specify the programming language as part of the deliverables? Regarding the cryptographic libraries, are you aware of similar existing libraries that you might be able to reuse?

2021-04-15 06:52 UTC, rubyprotocol commented
> Top proposal. So I imagine your first step of your M1.1 is to devise a Rust library for performing functional encryption like [GoFE](https://github.com/fentec-project/gofe) right? 

_Yes._ 

Are you going to base your work off an existing Rust project that does something similar? Also, do you plan to support all of modular arithmetic, pairings and lattices primitives or just focus on one of them?

_We plan to base our work on the CiFEr library (https://github.com/fentec-project/CiFEr) and its rust version (https://github.com/dev0x1/functional-encryption-schemes). We will mainly focus on supporting modular arithmetic and bilinear pairings._

2021-04-15 07:12 UTC, rubyprotocol commented
Thanks for your application. Looks interesting. What’s your relationship with the Kylin network? 

_Thanks. Dylan Dewdney is the CEO of Kylin network and will be our marketing advisor and our two projects will collaborate on data sharing. Beni Issembert was previously the CMO of Beam and the advisor of the Kylin network._ 

Do you have any previous code/experience which you could share? Could you specify the programming language as part of the deliverables? Regarding the cryptographic libraries, are you aware of similar existing libraries that you might be able to reuse?

2021-04-15 07:38 UTC, mmagician commented
> We plan to base our work on the CiFEr library (https://github.com/fentec-project/CiFEr) and its rust version (https://github.com/dev0x1/functional-encryption-schemes). We will mainly focus on supporting modular arithmetic and bilinear pairings.

So you're going to fork the rust version (and ideally contribute to it?). Would you mind outlining exactly the scope of changes needed to that rust library? As far as I can see, in its current form the lib supports only inner product (for pairings), so first you'd need to add quadratic polynomial FE, and then presumably do it for the two primitives you mentioned. Please correct me if I'm wrong - and otherwise, I'd appreciate if you could update the application document itself with this info. I would then be happy to support the project.

Regarding your previous work: it is not linked to your current profile in any way, and both @lornacrevelingwgo23 and @rubyprotocol profiles are quite empty. The repo you provided has been created just today. Is there any way you could perhaps provide better proof of previous experience?

2021-04-19 01:08 UTC, rubyprotocol commented
> https://github.com/fentec-project/CiFEr

2021-04-19 01:10 UTC, rubyprotocol commented
> > We plan to base our work on the CiFEr library (https://github.com/fentec-project/CiFEr) and its rust version (https://github.com/dev0x1/functional-encryption-schemes). We will mainly focus on supporting modular arithmetic and bilinear pairings.
> 
> So you're going to fork the rust version (and ideally contribute to it?). Would you mind outlining exactly the scope of changes needed to that rust library? As far as I can see, in its current form the lib supports only inner product (for pairings), so first you'd need to add quadratic polynomial FE, and then presumably do it for the two primitives you mentioned. Please correct me if I'm wrong - and otherwise, I'd appreciate if you could update the application document itself with this info. 

_Yes, you are totally right about the scope of changes to be done, and I have already updated the proposal accordingly. Thanks for pointing that out._ 

>I would then be happy to support the project.
 
_Great to know. Really appreciate your support._ 

> Regarding your previous work: it is not linked to your current profile in any way, and both @lornacrevelingwgo23 and @rubyprotocol profiles are quite empty. The repo you provided has been created just today. Is there any way you could perhaps provide better proof of previous experience?

2021-04-19 07:52 UTC, alxs approved these changes

2021-04-19 09:28 UTC, mmagician approved these changes
Fair, thanks for confirming and good luck with the project!

2021-04-19 11:51 UTC, Noc2 approved these changes

2021-04-19 11:51 UTC, merged

2021-04-19 12:17 UTC, rubyprotocol commented
> Fair, thanks for confirming and good luck with the project!

Thanks a lot for the support. You guys won't be disappointed.

2021-07-19 15:37 UTC, alxs commented
@rubyprotocol care to share a quick status update, along with an ETA if possible? We were hoping to receive your first delivery about 2 months ago now. As long as you're still working on the project, delays aren't a big problem, but if you're no longer interested we would terminate the grant. Besides, the usage of the grants badge on your [website](http://ruby.io/) goes against its guidelines (referred to by the bot two comments above mine) on two separate counts: it shouldn't be used on a team's landing page, and more importantly the grant shouldn't be announced publicly before your first milestone has been accepted, as clearly stated in the same comment.

I'd like to ask you to please remove the badge from your website and share some of your work with us or we'll be forced to terminate the grant due to breaching the [terms and conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T%26Cs.md).

2021-07-19 18:06 UTC, rubyprotocol commented
> @rubyprotocol care to share a quick status update, along with an ETA if possible? We were hoping to receive your first delivery about 2 months ago now. As long as you're still working on the project, delays aren't a big problem, but if you're no longer interested we would terminate the grant. Besides, the usage of the grants badge on your [website](http://ruby.io/) goes against its guidelines (referred to by the bot two comments above mine) on two separate counts: it shouldn't be used on a team's landing page, and more importantly the grant shouldn't be announced publicly before your first milestone has been accepted, as clearly stated in the same comment.
> 
> I'd like to ask you to please remove the badge from your website and share some of your work with us or we'll be forced to terminate the grant due to breaching the [terms and conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T%26Cs.md).

We will update our progress soon.

We did not announced publicly but we do list it on team's landing page. I have asked our website dev to remove the grants badge from all the relevant materials

2021-07-26 08:09 UTC, lornacrevelingwgo23 commented
> @rubyprotocol care to share a quick status update, along with an ETA if possible? We were hoping to receive your first delivery about 2 months ago now. As long as you're still working on the project, delays aren't a big problem, but if you're no longer interested we would terminate the grant. Besides, the usage of the grants badge on your [website](http://ruby.io/) goes against its guidelines (referred to by the bot two comments above mine) on two separate counts: it shouldn't be used on a team's landing page, and more importantly the grant shouldn't be announced publicly before your first milestone has been accepted, as clearly stated in the same comment.
> 
> I'd like to ask you to please remove the badge from your website and share some of your work with us or we'll be forced to terminate the grant due to breaching the [terms and conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T%26Cs.md).

_Hey Alex, sorry for the late response. We have been working on the code privately and did not update our repo in the Ruby project though. I guess we should have contact you more often. Here is our update: we have finished the coding of basic algorithms and their application on private machine learning. You can find the repo for the functional encryption in this repo: https://github.com/rubyprotocol/Functional_encryption_rust, and private machine learning in this repo: https://github.com/rubyprotocol/private_ml. We are working on the ZKP part and its integration with the Substrate pallet and expect Milestone 1 to be delivered soon. Meanwhile, we are also working on the design and development of UI in Milestone 2. _

2021-07-29 08:57 UTC, alxs commented
@lornacrevelingwgo23 thanks for the update. It looks like your code is mostly adapted from https://github.com/dev0x1/functional-encryption-schemes. Please make sure to attribute properly at the time of delivery. Could you please amend your application with a concrete estimate as for the delivery date?

2021-08-02 01:19 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for the update. It looks like your code is mostly adapted from https://github.com/dev0x1/functional-encryption-schemes. Please make sure to attribute properly at the time of delivery. 

_Thanks for your reminder. We will certainly attribute properly at the time of the official delivery._ 

Could you please amend your application with a concrete estimate as for the delivery date?

_It will take us some time to figure out how to import the ZKP library to the substrate module and we estimate it will probably take another two weeks to deliver milestone 1, and then another 1 month (as estimated in the original proposal) to deliver the milestone 2._

2021-08-02 16:53 UTC, alxs commented
In that case, could you please submit an amendment to increase M1's duration by 3 months (which would be the delay if you submitted in two weeks, feel free to make it 4 if you feel you may need more time)?

2021-08-03 11:31 UTC, lornacrevelingwgo23 commented
> In that case, could you please submit an amendment to increase M1's duration by 3 months (which would be the delay if you submitted in two weeks, feel free to make it 4 if you feel you may need more time)?

_Hey, already change the estimated duration of M1 from 1 month to 5 months. But we'll try to deliver before that._

2021-08-03 11:38 UTC, alxs commented
@lornacrevelingwgo23 not sure what you mean. You need to open a PR to modify your application.

2021-08-04 05:52 UTC, rubyprotocol commented
> @lornacrevelingwgo23 not sure what you mean. You need to create a PR to modify your application.

Thanks for your reminder. Already create a PR in this issue: https://github.com/w3f/Grants-Program/pull/555.

2021-11-26 16:44 UTC, mmagician commented
@rubyprotocol Do you have any updates regarding your second milestone? Are you still working on the project? Your delivery is overdue now, so if you could share your status that would be great. Otherwise, we would terminate your grant after 2 weeks unless we hear some news from you.

2021-11-30 01:07 UTC, lornacrevelingwgo23 commented
> @rubyprotocol Do you have any updates regarding your second milestone? Are you still working on the project? Your delivery is overdue now, so if you could share your status that would be great. Otherwise, we would terminate your grant after 2 weeks unless we hear some news from you.

Hey @mmagician , sorry for the late response. I haven't checked this repo for a while. We are still working on the project and will update our repo in a few days. We expect to deliver milestone 2 by the end of December.

2021-12-31 02:51 UTC, rubyprotocol commented
> @rubyprotocol Do you have any updates regarding your second milestone? Are you still working on the project? Your delivery is overdue now, so if you could share your status that would be great. Otherwise, we would terminate your grant after 2 weeks unless we hear some news from you.

Hey @mmagician , I have just created a pr for milestone 2 delivery: https://github.com/w3f/Grant-Milestone-Delivery/pull/332. Look forward to your comments.