add internft.md
w3f/Open-Grants-Program pull request #344
Opened 2021-04-02 08:40 UTC by web3hacker

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-04-02 08:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=344) it.</sub>

2021-04-03 08:09 UTC, Noc2 requested changes
Thanks for the application, but we would need more details in order to consider the application. For example how exactly does ccp work? How is it different from [this relayer](https://github.com/Snowfork/polkadot-ethereum/tree/main/relayer) written in go? Also as far as I know, snowfork is currently working on an nft example based on their bridge. What would be the advantage of using your solution? Do you have mockups for the front-end? Could you add the license, documentation, etc. to your delivery, see the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)?

2021-04-03 17:17 UTC, web3hacker commented
> Thanks for the application, but we would need more details in order to consider the application. For example how exactly does ccp work? How is it different from [this relayer](https://github.com/Snowfork/polkadot-ethereum/tree/main/relayer) written in go? Also as far as I know, snowfork is currently working on an nft example based on their bridge. What would be the advantage of using your solution? Do you have mockups for the front-end? Could you add the license, documentation, etc. to your delivery, see the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)?

Thanks for the review @Noc2

2021-04-03 17:20 UTC, web3hacker commented
> Thanks for the application, but we would need more details in order to consider the application. For example how exactly does ccp work? How is it different from [this relayer](https://github.com/Snowfork/polkadot-ethereum/tree/main/relayer) written in go? Also as far as I know, snowfork is currently working on an nft example based on their bridge. What would be the advantage of using your solution? Do you have mockups for the front-end? Could you add the license, documentation, etc. to your delivery, see the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)?

Thanks for the review @Noc2 

1. CCP is a modular multi-directional blockchain bridge to allow data and value transfer between any number of blockchains.  There are bridge contract (or pallet in Substrate) on each chain，The bridge  is maintained through a set of relayers that are authorized to make & process transfers across the different blockchains, random relayer using VRF.
2. Like Snowfork, CCP was inspired by Chainbridge, thanks to their work.
3. We believe that the security of NFT assets being transferred across chains is very important, low trust cross-chain NFT network are our focus. The CCP is finished  by randomly selecting nodes through VRF,  the security of the network is guaranteed by staking and a strict punitive PoS. 
4. front-end mockups: https://www.figma.com/file/Z1Mdrm0p6XXkeV0QXOeiIu/front-end.
5. The document has been updated.

>

2021-04-06 12:44 UTC, Noc2 commented
Thanks for the quick reply. However, the figman link, which you shared, only shows a single image to me. And since VRFs are currently not part of your grant proposal, I don’t see any advantage in your solution at the moment compared to chainbridge or even snowfork. 
Something to be aware of: Snowfork wasn’t inspired by Chainbridge. The bridge is implemented in a completely different way. Could try to improve the application another time, before I share it with the rest of the team?

2021-04-08 08:16 UTC, web3hacker commented
> Thanks for the quick reply. However, the figman link, which you shared, only shows a single image to me. And since VRFs are currently not part of your grant proposal, I don’t see any advantage in your solution at the moment compared to chainbridge or even snowfork.
> Something to be aware of: Snowfork wasn’t inspired by Chainbridge. The bridge is implemented in a completely different way. Could try to improve the application another time, before I share it with the rest of the team?

Thanks for the reply.  I have adjusted the latest architecture diagram. The contents of the Figman link have been filled in. I has updated the milestone 1.  Looking forward to your reply.

2021-04-12 13:52 UTC, Noc2 requested changes
Thanks for the update. Could you also integrate a comparison with chainbridge/snowfork into the application? For example how is your relayer different from the existing relayers? Independent of it and as promised, I will share your application with the rest of the team.

2021-04-13 09:07 UTC, web3hacker commented
> Thanks for the update. Could you also integrate a comparison with chainbridge/snowfork into the application? For example how is your relayer different from the existing relayers? Independent of it and as promised, I will share your application with the rest of the team.

Thank you Noc2, I updated Ecosystem Fit. This is our first application, we will complete Milestone 1 as soon as possible.

2021-04-13 10:20 UTC, alxs commented
Hi @web3hacker. We really would need more details in order to consider this application. Are you aware of [this treasury proposal](https://polkadot.polkassembly.io/post/349) and the discussion surrounding it that took place on Element a few weeks ago? How is your proposal different to that one? This would be very relevant to your application, which I think in general lacks significant technical as well as theoretical details concerning NFT migration, and seems detached from developments in the community.

> Internft is implemented by using the VRF to randomly select a node to attempt to solve the problem of low speed and high Gas for NFT cross-chain transfers, and effectively improve the security of managed assets through Punitive PoS and MultiSig.

How is this done? Do you have documentation, a whitepaper you could share? How does this solve low speed and high gas, and how do you leverage MultiSigs?

Do you have any prior work you could share, or involvement with the community?

2021-04-13 15:44 UTC, web3hacker commented
> Hi @web3hacker. We really would need more details in order to consider this application. Are you aware of [this treasury proposal](https://polkadot.polkassembly.io/post/349) and the discussion surrounding it that took place on Element a few weeks ago? How is your proposal different to that one? This would be very relevant to your application, which I think in general lacks significant technical as well as theoretical details concerning NFT migration, and seems detached from developments in the community.
> 
> > Internft is implemented by using the VRF to randomly select a node to attempt to solve the problem of low speed and high Gas for NFT cross-chain transfers, and effectively improve the security of managed assets through Punitive PoS and MultiSig.
> 
> How is this done? Do you have documentation, a whitepaper you could share? How does this solve low speed and high gas, and how do you leverage MultiSigs?
> 
> Do you have any prior work you could share, or involvement with the community?

Thanks for the review. 
1. [This treasury proposal ](https://polkadot.polkassembly.io/post/349) I understand it as a Top-down Design，hope to do a standard. The NFT as we understand it is a Long Tail market. Like the Ethereum ecosystem, NFT can be issued via ERC721, ERC-1155, or ERC20, the COMOS or EOS ecology will also be different.  We hope that through Bottom-up Design, Get the NFTs on the other chains to migrate to the Internft network as soon as possible and then into the Polkadot ecosystem. Such as our Milestone 1 will implement only one ERC721 migration, the Milestone 2/N iteration adapts the migrations of different NFT implementations on different chains.
2. Milestone 1 acts as a POC, Includes three whitelist nodes.  The node listens for the Deposit event of the NFT asset, which triggers the VRF of Internet Pallet_Bridge to randomly select the whitelist node, and then the asset is cast from this node; the Withdraw request of the user is similar and will be accompanied by the node's signature to verify the signature in the Ethernet contract, cooperate with the front end to complete NFT721 asset transfer for Ropsten and Internft.
3. Milestone 1 is about 3 weeks old, the tech whitepaper and Multisigs are still in pre-development.
4. We used to be the core developers of [Ares Protocol](https://github.com/aresprotocols), recently partnered with the Patract community to implement MakerDAO lending and Oracle feeding, [demo](https://github.com/ParityAsia/hackathon-2021-spring/tree/main/teams/24-Ares-Enthusiasts)

2021-04-13 17:59 UTC, semuelle commented
@web3hacker, do you have any online repositories or related profiles that show your involvement in any open source projects?

2021-04-14 01:53 UTC, lyxyx commented
> @web3hacker, do you have any online repositories or related profiles that show your involvement in any open source projects?

Hi @semuelle， I've been involved in some of these. [Ares Protocol](https://github.com/aresprotocols)

2021-04-14 15:00 UTC, semuelle commented
A relayer _just_ for NFTs seems way too specialised. This could be accomplished with XCMP or existing bridges. I am also concerned that both the internft and ares organisation have very little activity and few contributors on any of their repos.

2021-04-15 01:25 UTC, web3hacker commented
> A relayer _just_ for NFTs seems way too specialised. This could be accomplished with XCMP or existing bridges. I am also concerned that both the internft and ares organisation have very little activity and few contributors on any of their repos.

I was involved with the ARES project for the purpose of getting started and learning the Substrate framework, but now I am not an organization.

As a programmer, I just had a new idea and wanted to do something. Trust takes time to build, I'm not sure if there are other appropriate funding options for projects that are new to the Web 3.0 ecosystem and don't have much to show for it.

Considering the project itself, If the criteria for funding are not met, thank you very much for your time.

2021-04-16 18:41 UTC, Noc2 commented
Hi @web3hacker It’s definitely nice that you want to leverage substrate and work on your own project. That’s definitely something we want to support via the grants program. However, the main issue is that we have already funded multiple teams that are working on similar initiatives with a lot more resources and more detailed applications. I therefore suggest to close this application and instead to apply for something else, which is potentially more focused (e.g. a UI for existing pallets) or another more unique/niche project. Feel free to also take a look at our [project ideas section](https://github.com/w3f/Open-Grants-Program#project-ideas).

2021-04-16 22:02 UTC, semuelle commented
And feel free to reach out to us if you have any questions.

2021-04-17 01:11 UTC, web3hacker commented
Thank you very much @Noc2 @semuelle @alxs . I close this application. I will do a preliminary study independently, and I hope there will be an opportunity for cooperation in the near future.

2021-04-17 01:11 UTC, closed without merging