Create Toochain Protocol.md
w3f/Open-Grants-Program pull request #350
Opened 2021-04-03 21:52 UTC by toochaindev

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

2021-04-03 21:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=350) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=350) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=350) it.</sub>

2021-04-06 07:40 UTC, Noc2 requested changes
Thanks for the application. Could you please sign the CLA? Also, we've recently updated the application template to reflect the fact that grants now need to be denominated in USD (payment may still be in BTC or DAI). Could you update this?

2021-04-06 07:49 UTC, Noc2 commented
Furthermore, could you share more technical details and/or previous work? And just to clarify, does your first milestone enable me to write smart contracts in [glow](https://gitlab.com/mukn/glow) and run them on substrate?

2021-04-20 07:49 UTC, alxs commented
Closing due to inactivity. Feel free to reopen the application with the requested details.

2021-04-20 07:49 UTC, closed without merging