Create CryptoBot
w3f/Open-Grants-Program pull request #369
Opened 2021-04-14 15:42 UTC by Madao-3

# Grant Application Checklist

- [ ] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [ ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [ ] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

2021-04-14 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=369) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=369) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=369) it.</sub>

2021-04-14 17:42 UTC, alxs commented
I'm confused, this application is for a game but I don't see any section including game logic or mockups? Also please rename the file to `.md` so it is properly displayed.

2021-04-15 01:20 UTC, Madao-3 commented
> I'm confused, this application is for a game but I don't see any section including game logic or mockups? Also please rename the file to `.md` so it is properly displayed.

Just add a one pager GDD for this game. Please tell me if anything need to update

2021-04-16 05:41 UTC, Madao-3 commented
@semuelle Mostly my work is related to Ruby, but I participated in a lot of indie games jam.
My recent speech is `Component Based Rails Application-Ruby Summit 2018` and `When Ruby Met WebAssembly - 2020RubyConf SSR`.

Here is my Game Conpect
![image](https://user-images.githubusercontent.com/1069652/114976660-f0706180-9eb8-11eb-841c-cb12d316b590.png)
![image](https://user-images.githubusercontent.com/1069652/114976670-f403e880-9eb8-11eb-818e-244f860527ad.png)
![image](https://user-images.githubusercontent.com/1069652/114976679-f6fed900-9eb8-11eb-8bd2-3c8503a6aa22.png)
![image](https://user-images.githubusercontent.com/1069652/114976685-fa926000-9eb8-11eb-830a-624de374e779.png)
![image](https://user-images.githubusercontent.com/1069652/114976705-02ea9b00-9eb9-11eb-880e-cca4cdd0948a.png)

At this stage, I need the help of pixel artists and other developers 
What I can do: experience in web and smart contract development and overall project management.

2021-04-16 08:00 UTC, alxs commented
Looks neat, I quite like the concept. Could you integrate your experience and the mock-ups into the application (also keep this in mind for any future clarifications)?

What do you mean by
>  we will design a main line containing at least 50,000 words.

Also do you have any games you have previously worked on to show, and in which capacity?

Another question, would you consider splitting the work into several milestones? Ideally we'd like to hear something from you before the project is over, and in that way you would also get some funding midway.

Do you have any plans for deployment, e.g. will you launch your own substrate chain or will this just remain a PoC?

2021-04-16 08:53 UTC, Madao-3 commented
@alxs Thanks for your opinion, here is my answers:
> Could you integrate your experience and the mock-ups into the application (also keep this in mind for any future clarifications)? 
Sure! As a lifetime indie gamer/programmer. I can do it.

> we will design a main line containing at least 50,000 words.
sorry for the typo, it should be `we will design a story line containing at least 50,000 words`

> Another question, would you consider splitting the work into several milestones? Ideally we'd like to hear something from you before the project is over, and in that way you would also get some funding midway.
Good idea! Will update my milestone ASAP.

> Do you have any plans for deployment, e.g. will you launch your own substrate chain or will this just remain a PoC?
Good question, currently have several goals:
1. Implementation based on EVM
2. Can be abstracted into a protocol
3. Simplify development workflow
4. WASM friendly(optional)

My options will be these:
1. Moonbeam, developer-friendly workflow makes me feel good.
2. Plasm, according to my speech, You will know that one of my focuses is WASM.

2021-04-20 06:27 UTC, Madao-3 commented
Rename the game to `CryptoCitizen`, which is a more catchy name

2021-04-20 14:53 UTC, Noc2 requested changes
Thanks for the application. You say above that you plan an evm based implementation (Moonbeam, plasm), but your first milestone is actually to deliver substrate modules. What is correct? Also what functionality do you plan to integrate into the substrate modules and what do you want to store on-chain? It would probably be way too expensive to store all movements on-chain. Furthermore, have you already looked into other game related projects in our ecosystem? 

- https://github.com/bit-country/Bit-Country-Blockchain 
- https://github.com/creator-rs/creator/ 
- https://github.com/WiktorStarczewski/newomega.polkadot

2021-04-20 16:12 UTC, Madao-3 commented
> Also what functionality do you plan to integrate into the substrate modules and what do you want to store on-chain? It would probably be way too expensive to store all movements on-chain. Furthermore, have you already looked into other game related projects in our ecosystem?


@Noc2  Sorry for not updating this piece correctly. In order to make the game portable, We finally decided to make it base on Moonbeam.

And we will not store all movements on-chain, the detector we move to the server-side, we can just make player's gameplay results(what he gain) on-chain.  We modified it according to your suggestion.

Regarding the choice of Moonbeam, I need to explain: For the time being, based on the Polkadot ecological situation, the compatible solution proposed by Moonbeam is the best, and the feasibility of trying it is also the highest.

Thanks for recommending Bit-Country-Blockchain for giving me a lot of inspiration!

2021-04-20 20:05 UTC, alxs commented
So only the progress would be stored on chain?

> Sure! As a lifetime indie gamer/programmer. I can do it.

I think there was a misunderstanding here. I meant if you could please add the mockups and the experience you mentioned in your [comment](https://github.com/w3f/Open-Grants-Program/pull/369#issuecomment-820921677) to the proposal.

> Also do you have any games you have previously worked on to show, and in which capacity?

You forgot to answer this.

2021-04-21 00:42 UTC, Madao-3 commented
Hi @alxs, thx for the comment.
> So only the progress would be stored on chain?
Yes, players only have part of the settlement will onchain.

> I think there was a misunderstanding here. I meant if you could please add the mockups and the experience you mentioned in your comment to the proposal.
Already update my application.

> Also do you have any games you have previously worked on to show, and in which capacity?
I was been involved 2 times in [LD Game Jam](https://en.wikipedia.org/wiki/Ludum_Dare):
1. the First one is a programming & roguelike game. https://ldjam.com/events/ludum-dare/41/need-for-sleep
2. Keep Alex Alive https://ldjam.com/events/ludum-dare/46/keep-alex-alive

Because it is a product of Game Jam(for 48 hours), they are relatively immature. CryptoCitizen will not be a solo project, I will polish the game more complete

2021-04-21 10:09 UTC, alxs commented
Hi @Madao-3. I'm sorry to say I won't support this application due to the following reasons:
- It seems to me not a lot of thought was put into the technical aspects of the project, as you made fundamental decisions such as on which platform to build only as you were confronted with them.
- The two games you shared were very hard to play and as you say overall immature. I understand that these were built under a very short timeframe but for a Game Designer with 3 years of experience as you describe yourself in your application, I would have expected you to be able to share longer-term projects you were involved in.
- The application still lacks significant details, for example the section describing the game runtime would call for extensive technical details but you provide none.
- I didn't ask about this before, but why would you want to integrate a bridge to transfer NFTs from Ethereum? This doesn't make any sense to me.

I don't mean to discourage you from building this project, it seems like a cool idea. If you can put together a good team and build a PoC maybe you can apply again with more success.

Let's see if @Noc2 has any more questions then he might share your application with the rest of the team.

2021-04-21 11:17 UTC, Madao-3 commented
@alxs I understand your concern. The MVP of this game (not including blockchain) will be released in LD 48. You can choose according to your playing experience.

> I didn't ask about this before, but why would you want to integrate a bridge to transfer NFTs from Ethereum? This doesn't make any sense to me.

I am very reluctant to say that, but I am not optimistic about Polkadot's NFT market liquidity in a short period of time.

2021-04-21 11:25 UTC, alxs commented
But wouldn't _you_ create the NFTs used in the game?

2021-04-21 11:28 UTC, Madao-3 commented
> But wouldn't _you_ create the NFTs used in the game?

Ohhh, I got your point, here is a mistake, This description is before we decide to use Moonbeam, since we use this as our solution, we will not use Darwinia.

2021-04-21 11:40 UTC, alxs commented
I'm not sure we're talking about the same thing here. Being able to create your own NFTs on Polkadot as opposed to creating them on Ethereum and migrating them through a bridge (which is pointlessly complicated) doesn't depend on whether you deploy on Moonbeam or develop your own set of pallets.

2021-04-21 12:03 UTC, Madao-3 commented
@alxs Before we gradually perfected this solution, we prepared a multi-chain implementation model. At that time, Darwinia was a usable solution. After several optimizations, we only need to deploy the NFT contract on Polkadot. Because at this stage we only need the realization of a single chain.

2021-04-23 09:05 UTC, Noc2 requested changes
Thanks for the updates: So you want to leverage the moonbeam evm module, correct? In this case there should already be a lot of solidity based nft implementations out there, which you can simply reuse. Also the following delivery doesn’t make a lot of sense: “Smart Contract: Runtime” to me. Are you planning to develop a runtime or a smart contract or runtime module that allows the execution of smart contracts? Furthermore, you should be aware that we don’t support deliveries, which we can not verify or are useful for the rest of the ecosystem (e.g. “hire a designer” or “Deploy in Moonbase Alpha TestNet”)

2021-05-19 07:16 UTC, Noc2 commented
I’m closing this due to inactivity. Let me know if you want to re-open it.

2021-05-19 07:16 UTC, closed without merging