Add XCM Testsuite application
w3f/Open-Grants-Program pull request #375
Opened 2021-04-16 12:08 UTC by BoogerWooger

# Grant Application Checklist

- [X] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [X] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

2021-04-16 12:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=375) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=375) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=375) it.</sub>

2021-04-16 14:29 UTC, Noc2 requested changes
Thanks for the application. Are you aware of the following RFP: https://github.com/w3f/General-Grants-Program/blob/master/rfps/xcm-tool.md as well as this issue: https://github.com/paritytech/polkadot/issues/2544? It would be nice if you could coordinate with other teams interested in this tool, like for example Xiliang Chen from Acala, who created the issue. Additionally, could you maybe define the deliverables of the milestones and the specification a little bit more concrete? These are basically the requirements of the contracts and should be as detailed as possible.

2021-05-03 22:24 UTC, semuelle commented
Closing due to inactivity.

2021-05-03 22:24 UTC, closed without merging

2021-05-04 06:09 UTC, alxs commented
This looks like an interesting proposal, so just a note here: feel free to reopen the application as soon as you've addressed @Noc2's feedback.