Adds parachain staking
w3f/Open-Grants-Program pull request #389
Opened 2021-04-22 18:48 UTC by crystalin

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

2021-04-22 18:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=389) it.</sub>

2021-04-23 06:41 UTC, mmagician requested changes
@crystalin Thanks for the application, looks pretty good. The only change that I'd like to request is changing the currency, because as of recently we only pay in DAI for Open Grants.

2021-04-23 13:05 UTC, 4meta5 commented on applications/parachain-staking.md
> +* **Total Costs:** 0.6 BTC
```suggestion
* **Total Costs:** 30k DAI
```

2021-04-23 13:05 UTC, 4meta5 commented on applications/parachain-staking.md
> +* **Costs:** 0.4 BTC
```suggestion
* **Costs:** 20k DAI
```

2021-04-23 13:05 UTC, 4meta5 commented on applications/parachain-staking.md
> +* **Costs:** 0.2 BTC
```suggestion
* **Costs:** 10k DAI
```

2021-04-23 13:13 UTC, 4meta5 commented on applications/parachain-staking.md
> +* **Payment Address:** 1EMk3z9VMmXN6y3qwA37s6Qps4xRKGGE9G
@crystalin this needs to changed to a DAI address as well

2021-04-23 14:15 UTC, crystalin commented
The PR is not updating after pushing changes to the branch, I'm closing/re-opening the PR

2021-04-23 14:16 UTC, crystalin commented
@mmagician I've updated the currency/address

2021-04-29 05:50 UTC, Noc2 requested changes
Thanks for the application. Could you potentially also add the deliveries 0a to 0d to the application, see https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules. At least the license should be included. Regarding milestone 2, would it potentially be possible to also make a pr to integrate this into polkadot.js apps itself?

2021-04-30 04:34 UTC, 4meta5 commented
@Noc2 I made the requested changes, let me know if they are OK. I can change the licenses if necessary.

2021-04-30 07:20 UTC, mmagician approved these changes
Looks good to me, I'm looking forward to see this integrated!

2021-04-30 07:41 UTC, Noc2 approved these changes

2021-04-30 09:49 UTC, alxs approved these changes

2021-04-30 09:50 UTC, merged

2021-10-07 13:37 UTC, alxs commented
Hey @crystalin @4meta5, care to share a quick status update on your second milestone?

2021-10-18 15:42 UTC, alxs commented
@crystalin sounds good, thanks for the update. Please keep us posted.

2021-11-29 15:25 UTC, 4meta5 commented
@alxs 2 updates:
1. There was a recently significant refactor of the **1st milestone** `parachain-staking` pallet in https://github.com/PureStake/moonbeam/pull/810 . This PR changed the naming conventions from NPoS to DPoS. It also optimized the exits so that they are no longer scheduled to be automatically executed in `on_initialize` (which had led to large (sometimes overweight) blocks at round transitions). These changes are included in the upcoming NCC audit.
2. The **2nd milestone** work is complete https://github.com/polkadot-js/apps/pull/6430 but the PR is awaiting review. We are waiting for it to be approved and merged before formally submitting the milestone.