UpLink proposal
w3f/Open-Grants-Program pull request #424
Opened 2021-05-24 17:43 UTC by andre-francisco

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

2021-05-24 17:45 UTC, andre-francisco commented
Hi, all,

One quick note about this PR: there was a [similar PR before](https://github.com/w3f/Open-Grants-Program/pull/412), but the reviews were so extensive that we decided to open a new one. The old PR does not really contain any necessary information, but it feels better to clarify that and avoid any further confusion. Thank you.

2021-05-25 11:15 UTC, alxs commented
Thanks for the effort you've put into this @andre-francisco. You're right, this was very well explained and easier to understand. I only have these last remarks:
- I still wonder why the Android App is the first milestone, since if I understand correctly it would depend on deliverables from later milestones? You'd usually structure the milestones such that they can be delivered in order.
- Why is the price of M2 so much higher than all the others? I think the committee might be a bit taken aback by this, especially given that its description is more scarce than that of the other milestones. I understand that it includes research into Substrate (which, also, we usually unfortunately don't fund), but even with that I have a hard time justifying the price given the three features it provides. Could you potentially reduce the price or break down/expand on your cost estimate?
- And lastly, could you provide an estimate on the duration of each milestone in terms of weeks/months, so that there is a tentative deadline for each of them?

2021-05-25 14:08 UTC, andre-francisco commented
@alxs 

Thank you for your feedback, it makes a lot of sense.

I reordered the milestones and included a table with the order of the deliveries, I think this way it should be crystal clear, both for order and duration. Also, the Communication Protocol (which is now M1) was so expensive mostly because I was playing on the safe side with respect to the security assessment; those things are usually hard to predict because you don't know what you'll find in advance, but perhaps my hesitations were exaggerated; I've reduced the total cost.

Anything else you think I should do? Your feedback is super valuable, thank you, once again!

2021-05-25 16:07 UTC, andre-francisco commented
@alxs you're right, I missed that. It's fixed now. Thank you for status update, we'll be looking forward for next steps!

2021-05-25 17:03 UTC, alxs commented
Just a note in case there's any more feedback: no need to force-push any more. This is just for the initial PR, subsequent commits are useful as they allow us to see the changes.

2021-05-25 17:04 UTC, andre-francisco commented
@alxs Understood; I'll stop rebasing in the future.

2021-05-26 06:59 UTC, Noc2 requested changes
Thanks for the application. I have a few additional questions: 

- How do you plan to track the spent resources via substrate? I think this is one of the biggest problems to solve, because you quickly reach the limits of blockchains (tps) if you try to archive this in a way that can not be easily exploited. 
- In general, what do you plan to store on-chain? 
- Currently the relayer server seems to be rather centralized. Did you consider using something like an off-chain worker for this? How do you plan to incentivize people running the relayer?

2021-05-26 11:11 UTC, andre-francisco commented
@mmagician yes, it will. Citing from the proposal:

"In future reviews, this logic should be optionally integrated directly into Substrate, with the intent of having Substrate and off-the-grid devices communicate end-to-end, without the need for mediators. However, due to the complexity of that endeavour, the Relay Server will replace that setup for an initial version."

So the idea is that this communication protocol is made available as a Substrate module. That will probably be our followup for the General Grant program, since the implementation should be far more complex. For now we're using a Relay Server to replace that setup, but it's not ideal.

2021-05-26 11:28 UTC, andre-francisco commented
@Noc2 thank you for your questions, I'll leave some notes:

- How do you plan to track the spent resources via substrate? I think this is one of the biggest problems to solve, because you quickly reach the limits of blockchains (tps) if you try to archive this in a way that can not be easily exploited.

In this version the nodes are not incentivized. Citing the proposal: "It’s notable that this constitutes a relaxation of the UpLink project in many ways. In its entirety, the UpLink project proposes an incentive-based multi-hop mesh network system built on Substrate, enabling devices to communicate peer-to-peer and be rewarded for their cooperation. This project, however, proposes the much simpler non-rewarded proxy alternative [...]".

As for future versions, the incentivization model is not designed yet, but we're considering a model based on [Lot49](https://globalmeshlabs.org/files/Lot49%20Protocol%20Whitepaper%20-%20DRAFT%200.8.5_20190611.pdf), a mesh network incentivization model by goTenna. We're considering this as a followup for the General Grant program as well, or at least to have progress on this until then.

- In general, what do you plan to store on-chain?

Whatever the deployer wants. This is a generic system that enables devices to communicate, but it's up to specific implementations to decide what to do with it. That is, we work with connectivity, what that connectivity is used for is project-specific.

- Currently the relayer server seems to be rather centralized. Did you consider using something like an off-chain worker for this? How do you plan to incentivize people running the relayer?

The Relay Server will not be a part of the end system, but it will work as a means to implement the protocols and all the necessary logic until we get to the point where this is fully integrated into Substrate. It will work only for some use cases (e.g. the Relay Server can be trusted), but not for the general case; for that we'll need to go ahead with integrating the protocols as a Substrate module.

2021-05-27 06:45 UTC, Noc2 requested changes
Thanks for the quick reply. Yes states channels seem to be the best solutions for this problem at the moment. You should potentially take a look at [cChannel-substrate](https://github.com/celer-network/cChannel-substrate) by celer. Just one more question from my side: Do you already have some concrete initial use cases for your technology in mind?

2021-05-27 10:09 UTC, andre-francisco commented
We'll definitely have a look at cChannel-substrate, seems interesting. Thank you for the suggestion.

Regarding the use case, yes. We're working with a major payment processing company to enable digital payment processing in markets with poor or expensive connectivity, where digital banking and the usage of digital wallets is growing exponentially. This integration with Substrate will work as a key component of such system, and our goal is also to bring these payment processing companies closer to the crypto world; this integration should achieve just that.

2021-05-27 10:54 UTC, alxs approved these changes
Thank you for the answers @andre-francisco. Looks good from my side, wish you luck with the development!

2021-05-27 11:27 UTC, Noc2 approved these changes

2021-05-27 12:29 UTC, mmagician approved these changes

2021-05-27 12:33 UTC, merged

2021-10-14 13:19 UTC, andre-francisco commented
@alxs 

That is great to know! Reviewing the project proposal would be tricky at the moment, since all of our resources are currently allocated. But I'll make sure to update the proposal as soon as we can.

On another note, the first deliverable is actually ready; none of the other deliverables apply right now, but would it make sense to move forward with the first deliverable? What would that entail?

2021-10-14 20:53 UTC, alxs commented
@andre-francisco sounds good!

You can certainly submit the first milestone if it's ready - the only reason I can think of why you'd want to wait would be if you expect the rest of the project to change in a way that the milestone wouldn't fit into it any longer. As long as that isn't the case, please go ahead. The process is described in the [milestone delivery repo](https://github.com/w3f/Grant-Milestone-Delivery#mailbox-milestone-delivery-process). Please take care to complete documentation and test suite for the parts of the project that you intend to deliver and then simply follow the instructions! Let us know if you have any questions.

2021-12-22 11:35 UTC, alxs commented
@andre-francisco following up here, I hope everything's going well. Do you have any news on the project, and could you give us a quick update on the timeline? Depending on where you stand, it may make sense for you to submit that [amendment](https://github.com/w3f/Grants-Program/pull/424#issuecomment-942747840) now.

2022-01-06 10:05 UTC, alxs commented
@andre-francisco is this still on your roadmap? Note that given the delay and as we haven't heard from you in a while, we'd terminate the grant if we don't hear from you in the next 2 weeks. You're welcome to apply again at any time.