Create 1OS.md
w3f/Open-Grants-Program pull request #456
Opened 2021-06-15 19:58 UTC by kristopherleo

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

2021-06-15 19:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=456) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=456) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=456) it.</sub>

2021-06-16 07:09 UTC, Noc2 requested changes
Thanks for the application. I have a few questions: 

- Your website says that you will release the beta in 37 days, but your github organisation contains almost no code. Do you have private code, which you could potentially share?
- Our grants programs mostly focus on efforts related to Polkadot, Kusama and Substrate. Your current deliveries seem not directly related to this. Could you clarify this? 
- In general you mention a lot of things (CLI tool, D'App Deployment, etc.). There already tools for some of these components are you going to reuse these or to you want to develop everything from scratch? 
- I personally would say a “dapp” deployed to AWS is an app and not dapp, but this is up for discussion. 
- Doesn’t it make in general more sense to develop first the 1OS Testnet and later the UI for this? Why do you need a separate blockchain? In your image it looks like a blockchain agnostic UI.

2021-06-16 12:59 UTC, kristopherleo commented
Hello and thank you for your comments. 

Most certainly - I will respond to each question below:

- **Your website says that you will release the beta in 37 days, but your github organisation contains almost no code. Do you have private code, which you could potentially share?**

In terms of the 37 days mentioned on the 1OS website, this is purely a placeholder at this stage (which has not yet been announced - this will be made more clear on 1os.io). An accurate BETA launch date will depend on the project start date. We will confirm a start date as soon as possible and will then announce the finalized date via social media channels.

- **Our grants programs mostly focus on efforts related to Polkadot, Kusama and Substrate. Your current deliveries seem not directly related to this. Could you clarify this?**

The 1OS objective includes the enhancement of both the Substrate framework (for Blockchain creation), and also inherently becomes an important extension of the Polkadot Ecosystem:

**Substrate** - as an open-source framework, would inherit a publicly available Web3 API Library (nicknamed, Interoperable Layer) which will not only provide cross-chain interoperability to dapps deployed to the Web3 ecosystem - but to also enable any Web 3.0 dapp, protocol or smart contract to easily interact with other such entities, cross-chain. The Web3 API Library would contain subset clusters of API Services (inclusive of all dapps which opt to have their API services made available to the Library, as a deployable package - please see https://jfrog.com/artifactory/ this platform uses a similar approach), with an easy-to-use syntax. A similar technology to the Web3 API Library would be The Graph.

**Polkadot** - as an ecosystem focused on interoperability, would gain a rich and engaging Experience Layer in 1OS as a Cross-Chain Operating System, served not only to the fast-growing Polkadot & Kusama ecosystems of cross-chain DeFi protocols and dapps - but also inclusive of the wider Web 3.0 space (Ethereum, Binance Smart Chain, Bitcoin Lightning Network, Cardano, EOS, Neo, Tron etc.). 1OS provides a potentially very important layer of unification and infrastructure to Web 3.0 as a whole.

- In general you mention a lot of things (CLI tool, D'App Deployment, etc.). There already tools for some of these components are you going to reuse these or to you want to develop everything from scratch?

As a part of this process, more than receiving grant funding to support our development and research, we are even more interested in receiving any level of constructive criticism, recommendations (secure open-source tools), and additional team member support which may come from yourselves as the Web3 Foundation governing body and / or the surrounding Web3 community. 

In addition to this, within the original Open Grants application, there was the mention of Terminal Kit. This lib can be used in its entirety as a CLI tool, this will help with development speed as opposed to focusing too heavily on bespoke development. I am also happy to source a safe package and deployment tool. I have experience with Webpack and I am certain it may be purposed for our compiling, packaging and deployment needs (with some additional SSH executions).

- I personally would say a “dapp” deployed to AWS is an app and not dapp, but this is up for discussion.

I also agree with this point. However, to further clarify, 1OS deployments to AWS will only be the case in the 1OS BETA v1 release, which also serves as a proof-of-concept release. An alternate option would be to use **gh-pages** (an NPM package which many dapp developers use to host dapp assets / files via GitHub). However, with such a reliance on GitHub (a centralized organization / platform), such deployments are truly still not decentralized.

Longer term, 1OS will allow developers to deploy truly decentralized dapps via 1OS CLI. All deployed dapp asset's contents will be abstracted and served as static, immutable blockchain data on the Polkadot blockchain. All deployed assets will have URLs auto-generated, allowing the asset to be referenced in the browser, via URL. These specific behaviors within the deployment process would not be too dissimilar to that of a CDN (content delivery network). 

- Doesn’t it make in general more sense to develop first the 1OS Testnet and later the UI for this? Why do you need a separate blockchain? In your image it looks like a blockchain agnostic UI.

The primary reason for not developing the 1OS Testnet within the first release (BETA v1), is a challenge as a proof-of-concept, which proves to the wider Web3 community, that 1OS is truly blockchain agnostic, i.e. - 1OS can work with any blockchain. The 1OS Testnet / Mainnet would have only served to help with truly decentralized dapp deployments (as mentioned in answer to previous question) and for the benefit of low cost transactions for users etc.

In essence, any reference to the 1OS Testnet / Mainnet within our Open Grants application is interchangeable with the Polkadot network instead - as our main goal is to extend the Polkadot ecosystem and Substrate (as a framework) with highly innovative additional components, driving further interoperability and engagement / interaction with Web 3.0 as a whole - not to develop another blockchain.

Hopefully my answers make sense, however, if there is anything which needs further explanation or expansion, please do feel free to share further questions.

Thank you,
Leo

2021-06-16 13:02 UTC, kristopherleo commented
> Thanks for the application. I have a few questions:
> 
> * Your website says that you will release the beta in 37 days, but your github organisation contains almost no code. Do you have private code, which you could potentially share?
> * Our grants programs mostly focus on efforts related to Polkadot, Kusama and Substrate. Your current deliveries seem not directly related to this. Could you clarify this?
> * In general you mention a lot of things (CLI tool, D'App Deployment, etc.). There already tools for some of these components are you going to reuse these or to you want to develop everything from scratch?
> * I personally would say a “dapp” deployed to AWS is an app and not dapp, but this is up for discussion.
> * Doesn’t it make in general more sense to develop first the 1OS Testnet and later the UI for this? Why do you need a separate blockchain? In your image it looks like a blockchain agnostic UI.

Hello @Noc2 - please see my responsive above, thank you.

2021-06-17 10:05 UTC, Noc2 requested changes
Thanks for the response. In general feel free to integrate this also into the application, so that it’s easier for the rest of the committee to take a look at. I have a few follow up questions:

- In this case, wouldn’t it make sense to start working on the “Interoperable Layer” first? 
- Are you aware of [Substrate Interface API](https://github.com/polkascan/substrate-interface-api) and generally the work done by polkasan? This seems to cover already alot of the things, which you mentioned. 
- You compare your solution with the “The Graph”. How do you want to decentralize the  “Interoperable Layer” ? Also you might want to take a look at https://github.com/Joystream/hydra

2021-06-18 08:42 UTC, kristopherleo commented
Thank you for the follow up questions @Noc2 - Indeed, I am currently updating the original Application to include the information I previously shared in response to the first round of questions. This update will also contain some reform to the information shared regarding the Interoperable Layer. 

Please allow me until early next week (more than likely Monday) to make this update. The update will also answer the majority of your most recent questions, however, I will elaborate on the questions separately in addition to the application update.

Thank you,
Leo

2021-06-18 12:33 UTC, Noc2 commented
Thanks for the update. Feel free to take all the time you need. If you need more time, we could also close the PR and reopen it once you are ready. For now, I simply leave it open.

2021-06-30 12:56 UTC, Noc2 commented
I’m closing this for now. Let me know if I should reopen it.

2021-06-30 12:56 UTC, closed without merging

2021-07-06 01:32 UTC, kristopherleo commented
Thank you @Noc2, indeed - and I will be back in touch later.