Subdex
w3f/Open-Grants-Program pull request #60
Opened 2020-09-22 15:51 UTC by whalelephant

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [c] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

2020-09-22 15:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=60) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=60) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: whalelephant<br/>:x: fyang1024<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=60) it.</sub>

2020-09-22 18:15 UTC, Noc2 commented
Thanks for the application. @fyang1024 still needs to sign the cla assistant

2020-09-23 07:44 UTC, Noc2 approved these changes
Looks good to me.

2020-09-23 08:26 UTC, mmagician requested changes
@whalelephant Please specify the currency (BTC) of your milestone payment.

2020-09-23 09:44 UTC, mmagician approved these changes

2020-09-23 09:56 UTC, Noc2 approved these changes

2020-09-24 07:54 UTC, RouvenP approved these changes

2020-09-24 07:54 UTC, merged