integrate AssemblyScript to write substrate smart contract
w3f/Open-Grants-Program pull request #61
Opened 2020-09-23 07:38 UTC by synote

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

2020-09-23 07:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=61) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=61) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=61) it.</sub>

2020-09-23 09:24 UTC, Noc2 requested changes
Thanks for the application. I have a question regarding the first milestone. Rather than developing your own contract runtime module, wouldn’t it make more sense to leverage the existing contract module (https://github.com/paritytech/substrate/tree/master/frame/contracts) and write AS contracts that can be deployed to the existing module? What’s the reason for developing your own module? Independent of it, it would be nice to immediately have some example AS contract as part of milestone 1, which can be deployed for test purposes.

2020-09-23 09:56 UTC, synote commented
There is no plan to developing own contract runtime module. The milestone 1 will deliver an assemblyscript package will implement current substrate contract api and can be compiled to wasm to deploy on substrate node.

- contract runtime environment
- core types
- storage access
- object packing utilty
- memory manipulation
- contract event generation
- contract call method

All the iterms are just AS encapsulation of current substrate contract api. With the milestone 1 AS sdk, basic AssemblyScript contract demo can be deployed on substrate contract node, but with lack abstraction.

2020-09-23 10:28 UTC, Stefie commented
Hi @synote,
exiting to see the AssemblyScript Smart Contract development picking up!

I want to share a PoC implementation for Substrate Smart Contracts in AssemblyScript I was working on a few months ago.
The `as-contract` package in this repo  https://github.com/paritytech/as-substrate lets you write fully functional Contracts in AssemblyScript. It contains an implementation of the pallet contracts host functions, storage access, calling & executing contracts, basic crypto function implementation etc.

You can find some contracts examples in the [contracts](https://github.com/paritytech/as-substrate/tree/master/contracts) folder.

I haven't tested them with the more recent versions of Substrate so the implemented host functions are most likely outdated, but this repo will still be a good foundation  for you to get started. 

Feel free to reach out if you have any questions!

2020-09-23 15:33 UTC, synote commented
Nice to have the existing AS implementaion from as-substrate. The work of as-substrate will reduce our research time of current code of substrate smart contract. We will also benefit from ink's implementation and syntax.

Currently we only focus on AS smart contract and have no plan to support other substrate runtime.

2020-09-23 15:49 UTC, Stefie commented
> Currently we only focus on AS smart contract and have no plan to support other substrate runtime.
Sure! The runtime is being developed by LimeChain and they're pretty far along already

Small addition from my side: The host function prefix for callable contract functions changed from `ext_` to `seal_` mid august, so my implementation will definitely not work anymore. https://github.com/paritytech/substrate/commit/5f9e35531a854effbde948f9cb7df6ccd1ae2ddd

2020-09-24 15:34 UTC, synote commented
Thanks for the advice. We will deliver full implementation of latest substrate pallet contract specification.

2020-09-24 18:07 UTC, Noc2 requested changes
Thanks for the updates. Just one more question from my side: your original grants application was a little bit cheaper. I understand that you added a few additional points, but you are now also aware of additional code that you can leverage. So could you reduce the price a little bit? Also could you provide some basic documentation as part of the delivery? (On a side note, I’m currently on vacation, so I might be a little bit less responsive.)

2020-09-25 11:11 UTC, synote commented
> Thanks for the updates. Just one more question from my side: your original grants application was a little bit cheaper. I understand that you added a few additional points, but you are now also aware of additional code that you can leverage. So could you reduce the price a little bit? Also could you provide some basic documentation as part of the delivery?

We've reduced the milestone1 fund. The work of as-substrate and limechain will speed up our as contract delivery.

2020-09-26 13:56 UTC, Noc2 approved these changes
Looks good to me.

2020-09-26 15:27 UTC, gavofyork approved these changes

2020-09-28 07:42 UTC, RouvenP approved these changes

2020-09-28 07:42 UTC, merged

2021-05-27 10:06 UTC, alxs commented
Hi @synote. It was recently brought to our attention that TrustBase is advertising this grant on its [landing page](https://trustbase.network/). Could you quickly confirm whether you're involved with them? Furthermore, we would like to ask you to please remove prominent mentions of the grant such as that in the center of the website, as the grant was awarded for the development of Subscript but is unrelated to the TrustBase project. There is also no "Web3 Foundation Grant certification", you may instead state e.g. that the development of SubScript was supported by a Web3 Foundation grant. Allow me to refer you to our [Guidelines for the Web3 Foundation Grants Program Badge](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md), from which even though you're not using the badge and the grant is completed the following lines are relevant:

> Grants are awarded for specific projects, not to teams in general as a blanket endorsement.

and

> Also, please don't use the name or logo of the Web3 Foundation in any contexts that could misrepresent your relationship with Web3 Foundation. Infringement of these guidelines can result in an immediate annulment of the grant.

Thanks in advance.