PESA pallet
w3f/Open-Grants-Program pull request #69
Opened 2020-10-15 10:04 UTC by jdoshi1

# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.

2020-10-15 10:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=69) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=69) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=69) it.</sub>

2020-10-15 10:51 UTC, Noc2 requested changes
Thanks for the application. Looks very interesting. Could you also provide a little bit more information around the UI of the dapp. Which programming languages are you planning to use? Will it have a backend? Do you already have some mockups which you could share? Where can I learn more about your tokens and are you potentially planning to become a parachain?

2020-10-16 07:53 UTC, jdoshi1 commented
Thank you for reviewing our application, David. Appreciate the questions and happy to clarify. 

> Could you also provide a little bit more information around the UI of the dapp. 

It will be a web dapp where users can set a phone number to their wallet address. And send and receive tokens using the phone numbers.

> Which programming languages are you planning to use? 

The Pallet will be in Rust. Dapp will be in Angular/Javascript.

> Will it have a backend?

Yes, for verifying phone numbers through SMS OTP.

> Do you already have some mockups which you could share?

Yes. We have some draft mock ups. I’ll add it to the application.

> Where can I learn more about your tokens and are you potentially planning to become a parachain?

We haven’t made the tokenomics public yet so unfortunately don’t have anything to share at the moment. For the demo, we will just create a dummy token.

Regarding parachain, we plan to initially collaborate with an existing parachain and as we grow the network, if it made sense, we would explore becoming a parachain.

2020-10-18 09:48 UTC, Noc2 commented
Thanks for the quick reply. Could integrate this into the deliveries: “Dapp will be in Angular/Javascript” and potentially add more information. The tables with the deliverables are basically the requirements of the project. And I have one more request: Would it be possible to reduce the price of milestone 2 a little bit? Given that you estimated more work for milestone 1 but both cost currently the same.

2020-10-20 05:04 UTC, jdoshi1 commented
Thank you for reviewing the changes @Noc2 . There are couple of things in Milestone 2 as well - send, receive tokens and reverse resolution of address to phone number. Also, I missed adding backend as part of milestone 2 to provide SMS OTP for phone number verification. I've updated milestone 2 along with the duration.

2020-10-20 19:00 UTC, Noc2 commented
Two additional questions: Are you also planning to support DOT/KSM or to integrate your “PESA” token as parachain? Or is PESA deployed on a separate blockchain?

2020-10-20 22:21 UTC, NukeManDan commented
👋🏼  hey all - sorry for the intrusion, please let me know where is better to pose questions than here, I am unaffiliated, but excited by the proposal! I have a few questions:

- With the ongoing and quite lucrative [SIM swap attacks](https://www.zdnet.com/article/wave-of-sim-swapping-attacks-hit-us-cryptocurrency-users/), how do you propose to thwart this in your application?
- To that end, what audits on security are you planning on in the scope of this grant if any? (to prevent attacks like pre-provisioning keys, account recovery, ect.) 
- It seems you will rely on a central administrative backend to approve the key<->phone number mapping by a TOTP check. I would love to see this client oriented to generate and manage keys, as well as anchoring the mapping mechanism to a decentralized one. Is this something you would be able to do within this grant or as a next step? 

Excited to discuss here or another platform 😁 🙏🏼

2020-10-23 10:54 UTC, jdoshi1 commented
@Noc2 
> Two additional questions: Are you also planning to support DOT/KSM or to integrate your “PESA” token as parachain? Or is PESA deployed on a separate blockchain?

For the grant, we will create a substrate based chain with a dummy token for the demo. For the mainnet, we are talking to different potential parachains to integrate PESA pallet and will be supporting DOT/KSM, parachain native token and PESA governance token. Also open to creating our own parachain in the future. 

@NukeManDan 
> * With the ongoing and quite lucrative SIM swap attacks, how do you propose to thwart this in your application?

This is definitely one of the things we want to solve. However, it's still in the works and out of scope for this grant. Happy to chat offline.

> * To that end, what audits on security are you planning on in the scope of this grant if any? (to prevent attacks like pre-provisioning keys, account recovery, ect.)

It is out of scope for this grant but at the time of mainnet launch we will have it covered.

> * It seems you will rely on a central administrative backend to approve the key<->phone number mapping by a TOTP check. I would love to see this client oriented to generate and manage keys, as well as anchoring the mapping mechanism to a decentralized one. Is this something you would be able to do within this grant or as a next step?

Yes it is in our roadmap to have phone number verification/validation to be decentralized.

> Excited to discuss here or another platform 😁 🙏🏼

Thank you for your interest. You can reach out to [me](https://telegram.me/jdoshi1) or [Suruchi](https://telegram.me/iamsuruchi) on telegram 🙂

2020-10-27 09:55 UTC, Noc2 approved these changes
Thanks for the quick reply. I’m happy to go ahead with it and share it with the rest of the team. But I also want to point out that I see the centralization and security issues. It would be nice if these could be addressed together with the proof of concept or at least a more concrete idea on how to resolve it in the future would be helpful.

2020-10-28 09:48 UTC, mmagician commented
@jdoshi1 I like the idea behind your proposal, thanks for the submission.

I know there's already been a few questions regarding the backend, especially the issue regarding its centralisation. Still, I would like to ask you again for more technical details regarding your currently proposed solution. In particular: 
- It seems like your pallet doesn't have a method to `verify` a phone number (or perhaps it will be an internal method?) - how exactly will the blockchain communicate with your backend?
- Does your pallet need to know about the URL of the backend? Presumably, this is something that can be set during the deployment - this way you can support running a local backend too, am I right? Is there an option to later adapt the URL, and if so, how do you ensure not everyone can change it?
- What mechanism will you employ in order to prevent unauthorised calls to the `verify` method (either on the pallet or directly on the backend API)?

Thanks!

2020-11-01 10:48 UTC, jdoshi1 commented
Thanks for the approval, @Noc2 
Thank you for your questions @mmagician 

> I see the centralization and security issues. It would be nice if these could be addressed together with the proof of concept or at least a more concrete idea on how to resolve it in the future would be helpful.

Yes, agreed. We are still discussing within the team to see how we can make the phone number verification de-centralized. Initial thought is to have a group of validators for verifying a phone number. But we still need to architect and design how it would look like. This is something we would also like to closely work with you guys to get the design reviewed and approved.

> It seems like your pallet doesn't have a method to verify a phone number (or perhaps it will be an internal method?) - how exactly will the blockchain communicate with your backend?

Yes, currently it will be an internal method that is part of the register function. During registration, the pallet will interact with the backend to verify the phone number using a SMS OTP. Users will first verify their phone number by paying a small fee and the backend will store this transaction on the blockchain for each successful verification. Then the register function will communicate with the blockchain to finish registration and associate the phone number with the wallet address.

> Does your pallet need to know about the URL of the backend? Presumably, this is something that can be set during the deployment - this way you can support running a local backend too, am I right? Is there an option to later adapt the URL, and if so, how do you ensure not everyone can change it?

Yes that's correct, we would set the URL of the backend in the pallet. We are planning to only allow the URL to be set at the time of deployment and not be changed after that. 

> What mechanism will you employ in order to prevent unauthorised calls to the verify method (either on the pallet or directly on the backend API)?

We are thinking of charging a small fee per verify call to prevent this. This can be a parameter that can be adjusted by different projects.

2020-11-01 13:53 UTC, Noc2 approved these changes

2020-11-04 07:17 UTC, mmagician approved these changes
While there are still things that need ironing out around security and centralisation, I am curious to see the MVP!

2020-11-04 11:26 UTC, laboon commented
Are the numbers stored on the chain in plaintext or are they encrypted somehow?  If encrypted, how would decentralized verification work? (in theory, I know it's not part of the grant itself)

2020-11-06 10:14 UTC, jdoshi1 commented
Thank you @Noc2 @mmagician for the approvals. We are excited to build this! And definitely agree with your concerns as we have them too and are still working on trying to fix the centralized process of verification.

Thanks @laboon for your questions:

> Are the numbers stored on the chain in plaintext or are they encrypted somehow?

While testing on Ethereum, we created an NFT of the hashed phone number and so we are not storing the phone number directly in the contract. Just like how it is for ENS. We imagine it being something similar for substrate chain. 

> If encrypted, how would decentralized verification work? (in theory, I know it's not part of the grant itself)

For verification, we are using the SMS OTP to verify the phone number using a private backend before we allow them to create the NFT. This is something we are still discussing on how to make the phone number verification decentralized.

> If not encrypted (or trivially obscured), how would people be safe entering them on the chain?

I can see how this may be a concern for some. We aren’t really solving for privacy but ease of use for the real world users. One way to prevent this would be to use secondary numbers. We would be giving people an option to choose whether they would like to map their existing phone number or get a new number in the future. 

Also, making the phone number public is optional and so the reverse_look_up function will not reveal the phone number of a wallet address unless the wallet owner explicitly makes it public (on thinking more on it, it would be better to not provide the reverse_look_up functionality). Essentially the users would be using phone numbers for transacting with their contacts and for others they use their wallet address. The transactions won’t reveal the phone numbers but just the hash.

2020-11-09 08:07 UTC, laboon commented
Thanks @jdoshi1 !  Sounds like you and I have similar ideas about the problems and trade-offs.  Glad you are thinking about them now instead of trying to "just add in some privacy later". =)

2020-11-09 08:07 UTC, laboon approved these changes
👍

2020-11-09 08:17 UTC, merged

2020-11-11 08:05 UTC, jdoshi1 commented
Thank you @Noc2 @mmagician @laboon  for all the questions, comments and approval! :)

2021-05-19 16:56 UTC, alxs commented
Hi @jdoshi1. Care to share a quick status update? I had a brief look at your GitHub history and it seems the repositories for the first milestone delivery have been inactive for the past 3 months. If you're no longer interested, we would terminate the grant.

2021-06-05 18:19 UTC, alxs commented
The grant is now terminated due to inactivity.

2021-06-06 09:51 UTC, Noc2 commented
@jdoshi1 For your information, we terminated the grant due to inactivity, see https://github.com/w3f/Open-Grants-Program/pull/442. Feel free to apply again in case you are still interested in the project.