Saito - Polkadot Game Bridge - Open Grant Application
w3f/Open-Grants-Program pull request #73
Opened 2020-10-19 15:32 UTC by arpee

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

2020-10-19 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=73) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=73) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=73) it.</sub>

2020-10-20 08:29 UTC, mmagician commented
@arpee Thank you for the detailed application, I appreciate the effort put into preparing it. In my opinion, the idea is great and I would like to see such a protocol in the Polkadot ecosystem! That said, I have one conceptual question, let's take card dealing as an example:

I understand that randomness for dealing/shuffling cards comes from the blockchain, right? Therefore it must be publicly accessible to anyone wishing to inspect it. In such a case, how do you ensure that one player cannot discover the cards dealt privately to another player? I would be grateful if you could provide more details on how you plan to integrate the necessary secrecy into the game, yet at the same time ensuring all parties have the same information.

Many thanks!

2020-10-20 09:35 UTC, arpee commented
> @arpee Thank you for the detailed application, I appreciate the effort put into preparing it. In my opinion, the idea is great and I would like to see such a protocol in the Polkadot ecosystem! That said, I have one conceptual question, let's take card dealing as an example:
> 
> I understand that randomness for dealing/shuffling cards comes from the blockchain, right? Therefore it must be publicly accessible to anyone wishing to inspect it. In such a case, how do you ensure that one player cannot discover the cards dealt privately to another player? I would be grateful if you could provide more details on how you plan to integrate the necessary secrecy into the game, yet at the same time ensuring all parties have the same information.
> 
> Many thanks!

Hi @mmagician - thanks for the quick response.

We solve the problem you describe with a technique first developed by Shamir, Rivest and Adelman (the team after whom RSA encryption is named).  They developed a technique they called **Mental Poker** ( [original paper](https://people.csail.mit.edu/rivest/pubs/SRA81.pdf), [wikipedia](https://en.wikipedia.org/wiki/Mental_poker) ) that allows players to deal a deck in a provably fair way without a physical deck, and importantly for our use case, without an intermediary or trusted service.

Saito's development team spent several days working this problem before we hit the correct google search terms to unearth the answer. (We were frustratingly close, but had missed the importance of commutative encryption.)

Implementing this algorithm is somewhat time consuming and exactly the benefit the proposed gaming protocol and library gives to developers.  The protocol has implementations of this and other cryptographic techniques (you can quickly see how mental poker can be extended to provide other kinds of pre-shared but secret randomness). Using the library, game developers only need to define the decks required, and how to distribute these in a simple syntax. The underlying code then adds all the appropriate steps to the game stack, and co-ordinates their transmission and resolution over the network/blockchain. The same is true for die rolls, and other game actions. Saito uses the structure of a UTXO blockchain to create a public key infrastructure and network for sharing of such cryptographic payloads.

A non-generalized version of the game library and protocol are deployed and working on the [Saito Arcade](https://saito.io/arcade) where you can play poker today using this technique. 

I hope that answers your question. Please let me know if you would like us to add or extend the information in the application with this explanation.

We are also, of course, happy to take a call to provide more detail if that is useful.

2020-10-20 13:25 UTC, mmagician commented
@arpee Ah I see - I saw the link to the `Mental Poker` paper in your application, but somehow I missed its importance and the connection to the question I asked earlier.
It would be great if we could schedule a call, indeed. Perhaps you could reach out to me on Element at @marcin:web3.foundation to find a suitable time? Thanks

2020-10-20 13:45 UTC, mmagician submitted a review, later dismissed

2020-10-20 14:31 UTC, Noc2 requested changes
Thanks for the application. I have a few questions/comments:

- Could you reduce the overall price. It’s currently above 30k.
- Just for clarification “Saito Module” isn’t actually a substrate runtime module. It’s fully off chain (or take place on your own "layer-one blockchain" saito), correct? Or does it consist of a substrate runtime module as well as an off-chain “module”? 
- Regarding milestone 2, are things like “shuffling cards”, etc. actually recorded on-chain and if so on which chain? In general what information is stored on-chain? 
- Regarding milestone 3, here you plan to support DOTs or KSM as an asset, correct?

2020-10-20 15:05 UTC, arpee commented
> Thanks for the application. I have a few questions/comments:
> 
> * Could you reduce the overall price. It’s currently above 30k.
[x] - I have adjusted the price down to reflect current BTC price. I had ensured it was below 30k CHF not realizing the current strength of the CHF/USD.
> * Just for clarification “Saito Module” isn’t actually a substrate runtime module. It’s fully off chain (or take place on your own "layer-one blockchain" saito), correct? Or does it consist of a substrate runtime module as well as an off-chain “module”?
[x] This is correct, the Saito module would create a bridge to allow data to be sent to substrate 'as is'.
> * Regarding milestone 2, are things like “shuffling cards”, etc. actually recorded on-chain and if so on which chain? In general what information is stored on-chain?
[x] As per the proposal - these would be stored/transmitted on Saito's transient cryptographic ledger. The information could be summarized in part (e.g. Merkle root) or whole and added to relevant chains along with payouts or NFT for token transfer etc when needed. 
> * Regarding milestone 3, here you plan to support DOTs or KSM as an asset, correct?
[x] This might be best taken on advisement, the decision likely being based on what is most suitable for developers in the Polkadot ecosystem to support adoption.

For all the the last three points we would be happy to take advise to maximize the utility of the proposal.

2020-10-21 14:57 UTC, laboon commented
I like this idea and think it provides something REALLY valuable to the ecosystem, and takes blockchain gaming in a very different (and good!) direction.  The Saito site linked had a few games and provides one of the better POC's I have seen.  There were a few minor issues (I got rid of my chat box and I kept getting notifications that my opponent was messaging me but I couldn't message back...) but it was very impressive.

The one thing I might change is that there would be a connection to a parachain instead of directly to the relay chain, but since parachains won't be coming to Polkadot for a bit, I would be totally fine with connecting to the relay chain (and dealing with DOT and KSM) for now.  Connection to e.g. Acala in the future would be a good opportunity for growth.

2020-10-23 10:08 UTC, arpee commented
@mmagician - just letting you know we have updated the application in light of our last discussion. 

Specifically we have changed the deliverables and updated the approach on your suggestions and to better align with the goals of the grant program.

Thanks for the feedback and hope this makes sense.

2020-10-26 04:11 UTC, arpee commented
@laboon 
> The one thing I might change is that there would be a connection to a parachain instead of directly to the relay chain, but since parachains won't be coming to Polkadot for a bit, I would be totally fine with connecting to the relay chain (and dealing with DOT and KSM) for now. Connection to e.g. Acala in the future would be a good opportunity for growth.

We are happy to take advice on the way to be most productive, especially on this aspect of things.

Will dig into Acala.

2020-10-27 17:09 UTC, arpee commented
@mmagician and @Noc2 - I adjusted the requested size of the grant down in view of BTC price movements.

2020-10-29 12:14 UTC, mmagician commented
@arpee Thanks for updating the application following our conversation.

There's just one comment from my side:
Initially the total cost for M1: "Saito Polkadot API Module" and M3: "Milestone 3 — Asset Transfers in Gaming Protocol" was 0.5 + 0.75 = 1.25 BTC. After you've removed non-Polkadot specific M2, the total cost for the mentioned deliverables has gone up to 2.2 BTC.
I haven't noticed any significant additions to the list of deliverables, therefore may I ask you to keep the original price?

Otherwise the proposal looks good & I'll be happy to move forward.

2020-10-30 14:46 UTC, arpee commented
@mmagician 

Regarding the scope and requested funds - given the feedback here and from our conversation on the call we refactored the work to be more practical and focus on tangible deliverables. Specifically moving the original M2 out of scope. 

We added building and running a working environment running a Polkadot (testnet) node and Satio node deploying the software. M1.3. Similarly we added a week to our timline expectations for the new M2 (original M3) regarding creating a game for this environment demonstrating payments and interoperability.

This resulted in some of the work we envisaged around the body of the original M2 going to the other two milestones.

That being said - we are happy to consider adjusting the requested size of the grant if the requested amount is an issue or out of step with other grants awarded.

2020-10-30 15:54 UTC, mmagician commented
@arpee Thanks for a quick reply, below are my comments:
> We added building and running a working environment running a Polkadot (testnet) node

This is a necessary part of building a Substrate module (which is M1.1), since to properly build & verify a module, you should test it on a local node anyway. Or do you mean you'll deploy a public testnet?

> Saito Stack

As I understood from our conversation, you already have Satio Stack up & running, right? How does this deliverable differ from what you already have? If different - could you please provide more details on what are the components of the stack that you'll deliver for this milestone?

> Similarly we added a week to our timeline expectations for the new M2 (original M3) regarding creating a game for this environment demonstrating payments and interoperability

Your [original application](https://github.com/w3f/Open-Grants-Program/pull/73/commits/c76b45873b463a2aa4a87f563c6a2a032b6b50f8) already contains that part.

Also, thanks for being flexible about the cost. As per my comments here, I would like to stick to the original M2 price (0.75 BTC), unless you think I've missed some important details. Regarding M1, it would be great if you could please clarify my doubts here first before discussing which price version we go with :)

Looking forward to your reply!

2020-11-02 07:23 UTC, arpee commented
> @arpee Thanks for a quick reply, below are my comments:
> 
> > We added building and running a working environment running a Polkadot (testnet) node
> 
> This is a necessary part of building a Substrate module (which is M1.1), since to properly build & verify a module, you should test it on a local node anyway. Or do you mean you'll deploy a public testnet?

Yes, we intend to extend this to creating a public testnet implementation.
> 
> > Saito Stack
> 
> As I understood from our conversation, you already have Satio Stack up & running, right? How does this deliverable differ from what you already have? If different - could you please provide more details on what are the components of the stack that you'll deliver for this milestone?
> 
> > Similarly we added a week to our timeline expectations for the new M2 (original M3) regarding creating a game for this environment demonstrating payments and interoperability
> 
> Your [original application](https://github.com/w3f/Open-Grants-Program/pull/73/commits/c76b45873b463a2aa4a87f563c6a2a032b6b50f8) already contains that part.
> 
> Also, thanks for being flexible about the cost. As per my comments here, I would like to stick to the original M2 price (0.75 BTC), unless you think I've missed some important details. Regarding M1, it would be great if you could please clarify my doubts here first before discussing which price version we go with :)

I'm happy to adjust to that to keep this moving forward, no need to stall things over 0.15BTC.
> 
> Looking forward to your reply!

I have updated accordingly,

Richard

2020-11-04 07:32 UTC, mmagician commented
@arpee Looks good, thanks for addressing my comments. Just one more formality regarding the following:

> Yes, we intend to extend this to creating a public testnet implementation.

Could you please add a line mentioning the deployment of a public testnet in Milestone 1.3 within your application?

As soon as you've done that, we're good to go from my side & I'll share the application with other team members. Thanks!

2020-11-04 08:04 UTC, arpee commented
@mmagician - done.

2020-11-04 08:31 UTC, mmagician approved these changes

2020-11-04 09:46 UTC, Noc2 approved these changes
Looks good. But it would be nice if you could also support Kusama/KSM. Also given that I think Kusama is a very good fit for gaming focused applications.

2020-11-04 12:45 UTC, laboon approved these changes

2020-11-04 12:52 UTC, merged

2021-06-04 03:32 UTC, trevelyan commented
yes we are actively working. update soon.

2021-06-04 06:44 UTC, arpee commented
Hi @mmagician - sorry for the tardiness on this. We have actually had running code for some time on this. We are buttoning up the submission and hope to have it to you shortly.

I have also reached out directly on element with some more general questions.

2021-06-07 10:59 UTC, arpee commented
Hi @mmagician - we have a pull request ready to go but are blocked on - https://github.com/w3f/Grant-Milestone-Delivery/issues/187 (the link to the google form is down/returning that the form is deleted)

I have the repo ready to submit as a pull request and can send any time.