add dwitter.md
w3f/Open-Grants-Program pull request #85
Opened 2020-11-01 14:19 UTC by goldfink

# Grant Application Checklist

- [X] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] A BTC address for the payment of the milestones is provided inside the application.  
- [X] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [X] The total funding amount of the project is below CHF 30k at the time of submission.

2020-11-02 10:04 UTC, Noc2 requested changes
Thanks for the application. This sounds really interesting. A few questions/comments from my side: 

- Could you change the total amount of the grant to BTC (since this is a requirement of the open grants program)? 
- Could you integrate unit tests into your deliverables? 
- How is your dns solution different from https://github.com/xaya/substrate-names. 
- Are you planning to use the above implementation? 
- Btw. you could potentially also apply for https://github.com/filecoin-project/devgrants. Let me know in case this sounds interesting to you and I can put you in contact with the team.

2020-11-02 10:08 UTC, Noc2 commented
Regarding the MetaMask integration: 
- You can take a look at https://github.com/paritytech/frontier 
- And https://github.com/NodeFactoryIo/metamask-snap-polkadot

2020-11-02 10:32 UTC, goldfink commented
Hello! Commenting inline.

> Thanks for the application. This sounds really interesting. A few questions/comments from my side:
Thanks! This platform and service would mean a lot to us and many people!

> * Could you change the total amount of the grant to BTC (since this is a requirement of the open grants program)?
Done!

> * Could you integrate unit tests into your deliverables?
Done, also benchmarks.

> * How is your dns solution different from https://github.com/xaya/substrate-names.
We were aiming to use substrate-names for unique identifiers, we are just not yet sure on how to expose the platform to the public DNS and web3. Added a substrate-name module to deliverable to be clear that we are using Polkadot/Substrate for Unique Names.

> * Are you planning to use the above implementation?
Yes.

> * Btw. you could potentially also apply for https://github.com/filecoin-project/devgrants. Let me know in case this sounds interesting to you and I can put you in contact with the team.

Thanks! Will Do!

2020-11-02 10:45 UTC, Noc2 submitted a review, later dismissed
Thanks. Looks good. I will share it with the rest of the team.

2020-11-03 18:13 UTC, goldfink commented
@Noc2 I added Filecoin in potential replacement of IPFS and updated the BTC CHF exchange rate with a Unix Timestamp to indicate a total amount of 30,000 CHF project funding. I kindly request to re-approve for review.

2020-11-03 22:28 UTC, goldfink commented
Adding @rphmeier and @jplatts12 in response to @Noc2 👍

2020-11-04 07:47 UTC, mmagician approved these changes

2020-11-04 08:09 UTC, Noc2 approved these changes

2020-11-04 12:31 UTC, laboon commented on applications/dwitter.md
> +Previous social networking solutions like Diaspora or Mostadon have either failed to reach social outreach, or have failed in their purpose of censorship resistance for an open and inclusive web3. Cu
_Previous social networking solutions like Diaspora or Mostadon have either failed to reach social outreach, or have failed in their purpose of censorship resistance for an open and inclusive web3._

Can you explain why you think this would succeed where those have not?  Is it due to the social payments mentioned below?

2020-11-04 13:08 UTC, goldfink commented on applications/dwitter.md
> +Previous social networking solutions like Diaspora or Mostadon have either failed to reach social outreach, or have failed in their purpose of censorship resistance for an open and inclusive web3. Cu
> _Previous social networking solutions like Diaspora or Mostadon have either failed to reach social outreach, or have failed in their purpose of censorship resistance for an open and inclusive web3._
> 
> Can you explain why you think this would succeed where those have not? Is it due to the social payments mentioned below?

Whereas Diaspora and Mostadon are lacking fully decentralized infrastructure suitable for a single user to host content comfortably or to host as much of it as possible through technologies like IPFS or Filecoin, the architecture rather implies, so does Mostadon, the use of server nodes, and did not / does not have access to the Blockchain ecosystem or IPFS/Filecoin, neither did it at the point of time of its inception. Neither of the platforms do include or advertise Anonymity, for example through Tor circuits, and we consider it important to post securely from around the world without being detained for Freedom of Speech. Also Diaspora's initial funding was rather minor and it was not branded or set up as a startup company with that funding, aiming to reach maximum growth but remained a Proof-Of-Concept. We are establishing a fully branded platform and startup company.

Mostadon is open-source and allows for the hosting of nodes, but isn't intended to be censorship resistant, isn't executing upon it in production and is gaining press for endorsing censorship. It relies heavily on centralized infrastructure on its public platform. We are solely operating infrastructure with zero insight into user doings and interfacing with the Blockchain / Encrypted self-hosted User Storage through IPFS or Filecoin, and store private messages encrypted as well as supporting comfortable payment. This matters to users like Diplomatic Missions which use Twitter heavily for International Exchange, but are currently limited in their ability to reach out to users discretely and without giving the U.S. advantage in knowing about the Direct Message.

Dwitter aims to rely heavily on Blockchain and user-friendly self-hosted Decentralization/Storage with human readable names and comfortable social payments heavily integrated into the platform, as well as building a fully branded and marketed startup company with its anonymous and decentralized services attached to the public DNS, reward/incentivation for A-List prominencies such as J.K. Rowling or Reese Witherspoon discussing Bitcoin publicly on Twitter currently, to use it. The outreach of prominencies to fans should be rewarded, and the discrete outreach of politicans or embassies to arbitrary users, as well as inter-embassy or for example UN/NATO mission exchange, should be accomplished with ease and reliably secure, on a platform that is not Proof-Of-Concept but renders a new web3 standard.

2020-11-04 13:36 UTC, laboon commented on applications/dwitter.md
> +Previous social networking solutions like Diaspora or Mostadon have either failed to reach social outreach, or have failed in their purpose of censorship resistance for an open and inclusive web3. Cu
Sounds good, thank you.

2020-11-04 13:36 UTC, laboon approved these changes

2020-11-04 13:54 UTC, merged

2020-11-04 14:58 UTC, goldfink commented
What's the process to change the project URL to https://github.com/goldfink/follow ? This is where development will happen

2020-11-04 17:07 UTC, Noc2 commented
@goldfink I updated it in the [grants accepted list](https://github.com/w3f/General-Grants-Program/blob/master/grants/accepted_grant_applications.md). I don’t think it’s necessary to update it here.

2020-11-04 20:52 UTC, goldfink commented
> @goldfink I updated it in the [grants accepted list](https://github.com/w3f/General-Grants-Program/blob/master/grants/accepted_grant_applications.md). I don’t think it’s necessary to update it here.

Thanks!