Draft/api service grant
w3f/Open-Grants-Program pull request #99
Opened 2020-11-13 00:06 UTC by ianhe8x

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

2020-11-13 00:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=99) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=99) it.</sub>

2020-11-13 16:47 UTC, Noc2 requested changes
Thanks for the application. Something to be aware of is that we usually focus with the grants program on the development of open source software, which also can be used by others for their own projects. It seems your grant proposal is highly focused on your existing solution. Are you planning to open source it? If this isn’t the case, I suggest to apply for funding via the treasuries instead. I therefore told Ben to put you in contact with Raul.

2020-11-14 04:23 UTC, ianhe8x commented
That was also my doubt, thanks for clarifying it.

2020-11-16 08:17 UTC, Noc2 commented
I will close the application for now. Feel free to reopen it, in case you still want to apply via the open grants program.

2020-11-16 08:17 UTC, closed without merging